apiVersion: applications.authentik.crossplane.io/v1alpha1
kind: Entitlement
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1alpha1/entitlement
  labels:
    testing.upbound.io/example-name: ent
  name: ent
spec:
  forProvider:
    applicationSelector:
      matchLabels:
        testing.upbound.io/example-name: name
    name: test-ent

---

apiVersion: applications.authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1alpha1/entitlement
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: example-app
    slug: example-app

---

apiVersion: users.authentik.crossplane.io/v1alpha1
kind: Group
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1alpha1/entitlement
  labels:
    testing.upbound.io/example-name: group
  name: group
spec:
  forProvider:
    name: test-ent-group

---

apiVersion: policies.authentik.crossplane.io/v1alpha1
kind: Binding
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1alpha1/entitlement
  labels:
    testing.upbound.io/example-name: test-ent-access
  name: test-ent-access
spec:
  forProvider:
    groupSelector:
      matchLabels:
        testing.upbound.io/example-name: group
    order: 0
    targetSelector:
      matchLabels:
        testing.upbound.io/example-name: ent
