apiVersion: applications.unbounded-tech.com/v1alpha1
kind: ProviderScim
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1alpha1/providerscim
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: test-app
    propertyMappingsGroupRefs:
    - name: authentik_property_mapping_scim
    propertyMappingsRefs:
    - name: authentik_property_mapping_scim
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    url: http://localhost
