apiVersion: applications.unbounded-tech.com/v1alpha1
kind: ProviderProxy
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1alpha1/providerproxy
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    authorizationFlowSelector:
      matchLabels:
        testing.upbound.io/example-name: authentik_flow
    externalHost: http://internal.service
    internalHost: http://foo.bar.baz
    name: test-app

---

apiVersion: applications.unbounded-tech.com/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: applications/v1alpha1/providerproxy
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: test-app
    protocolProviderSelector:
      matchLabels:
        testing.upbound.io/example-name: name
    slug: test-app
