// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RuleInitParameters struct {

	// Send notification to event user Defaults to `false`.
	DestinationEventUser *bool `json:"destinationEventUser,omitempty" tf:"destination_event_user,omitempty"`

	// Group to send notification to
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/users/v1alpha1.Group
	DestinationGroup *string `json:"destinationGroup,omitempty" tf:"destination_group,omitempty"`

	// Reference to a Group in users to populate destinationGroup.
	// +kubebuilder:validation:Optional
	DestinationGroupRef *v1.Reference `json:"destinationGroupRef,omitempty" tf:"-"`

	// Selector for a Group in users to populate destinationGroup.
	// +kubebuilder:validation:Optional
	DestinationGroupSelector *v1.Selector `json:"destinationGroupSelector,omitempty" tf:"-"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Allowed values:
	// - `notice`
	// - `warning`
	// - `alert`
	// Defaults to `warning`.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	Transports []*string `json:"transports,omitempty" tf:"transports,omitempty"`
}

type RuleObservation struct {

	// Send notification to event user Defaults to `false`.
	DestinationEventUser *bool `json:"destinationEventUser,omitempty" tf:"destination_event_user,omitempty"`

	// Group to send notification to
	DestinationGroup *string `json:"destinationGroup,omitempty" tf:"destination_group,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Allowed values:
	// - `notice`
	// - `warning`
	// - `alert`
	// Defaults to `warning`.
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	Transports []*string `json:"transports,omitempty" tf:"transports,omitempty"`
}

type RuleParameters struct {

	// Send notification to event user Defaults to `false`.
	// +kubebuilder:validation:Optional
	DestinationEventUser *bool `json:"destinationEventUser,omitempty" tf:"destination_event_user,omitempty"`

	// Group to send notification to
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/users/v1alpha1.Group
	// +kubebuilder:validation:Optional
	DestinationGroup *string `json:"destinationGroup,omitempty" tf:"destination_group,omitempty"`

	// Reference to a Group in users to populate destinationGroup.
	// +kubebuilder:validation:Optional
	DestinationGroupRef *v1.Reference `json:"destinationGroupRef,omitempty" tf:"-"`

	// Selector for a Group in users to populate destinationGroup.
	// +kubebuilder:validation:Optional
	DestinationGroupSelector *v1.Selector `json:"destinationGroupSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Allowed values:
	// - `notice`
	// - `warning`
	// - `alert`
	// Defaults to `warning`.
	// +kubebuilder:validation:Optional
	Severity *string `json:"severity,omitempty" tf:"severity,omitempty"`

	// +kubebuilder:validation:Optional
	Transports []*string `json:"transports,omitempty" tf:"transports,omitempty"`
}

// RuleSpec defines the desired state of Rule
type RuleSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RuleInitParameters `json:"initProvider,omitempty"`
}

// RuleStatus defines the observed state of Rule.
type RuleStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Rule is the Schema for the Rules API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Rule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.transports) || (has(self.initProvider) && has(self.initProvider.transports))",message="spec.forProvider.transports is a required parameter"
	Spec   RuleSpec   `json:"spec"`
	Status RuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RuleList contains a list of Rules
type RuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Rule `json:"items"`
}

// Repository type metadata.
var (
	Rule_Kind             = "Rule"
	Rule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Rule_Kind}.String()
	Rule_KindAPIVersion   = Rule_Kind + "." + CRDGroupVersion.String()
	Rule_GroupVersionKind = CRDGroupVersion.WithKind(Rule_Kind)
)

func init() {
	SchemeBuilder.Register(&Rule{}, &RuleList{})
}
