apiVersion: customization.unbounded-tech.com/v1alpha1
kind: PropertyMappingSourceLdap
metadata:
  annotations:
    meta.upbound.io/example-id: customization/v1alpha1/propertymappingsourceldap
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    expression: return ldap.get('sAMAccountName')
    name: custom-field
