apiVersion: customization.unbounded-tech.com/v1alpha1
kind: PropertyMappingProviderScope
metadata:
  annotations:
    meta.upbound.io/example-id: customization/v1alpha1/propertymappingproviderscope
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    expression: |
      return {
        "policy": "readwrite",
      }
    name: minio
    scopeName: minio
