apiVersion: rbac.authentik.crossplane.io/v1alpha1
kind: PermissionRole
metadata:
  annotations:
    meta.upbound.io/example-id: rbac/v1alpha1/permissionrole
  labels:
    testing.upbound.io/example-name: global-permission
  name: global-permission
spec:
  forProvider:
    permission: authentik_flows.inspect_flow
    roleSelector:
      matchLabels:
        testing.upbound.io/example-name: my-role

---

apiVersion: flows.authentik.crossplane.io/v1alpha1
kind: Flow
metadata:
  annotations:
    meta.upbound.io/example-id: rbac/v1alpha1/permissionrole
  labels:
    testing.upbound.io/example-name: flow
  name: flow
spec:
  forProvider:
    designation: authorization
    name: test-flow
    slug: test-flow
    title: Test flow
