apiVersion: stages.authentik.crossplane.io/v1alpha1
kind: AuthenticatorTotp
metadata:
  annotations:
    meta.upbound.io/example-id: stages/v1alpha1/authenticatortotp
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: totp-setup
