apiVersion: stages.authentik.crossplane.io/v1alpha1
kind: AuthenticatorWebauthn
metadata:
  annotations:
    meta.upbound.io/example-id: stages/v1alpha1/authenticatorwebauthn
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: webauthn-setup
