// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RedirectInitParameters struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	KeepContext *bool `json:"keepContext,omitempty" tf:"keep_context,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `static`
	// - `flow`
	// Defaults to `flow`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	TargetFlow *string `json:"targetFlow,omitempty" tf:"target_flow,omitempty"`

	// (String)
	TargetStatic *string `json:"targetStatic,omitempty" tf:"target_static,omitempty"`
}

type RedirectObservation struct {

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	KeepContext *bool `json:"keepContext,omitempty" tf:"keep_context,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `static`
	// - `flow`
	// Defaults to `flow`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	TargetFlow *string `json:"targetFlow,omitempty" tf:"target_flow,omitempty"`

	// (String)
	TargetStatic *string `json:"targetStatic,omitempty" tf:"target_static,omitempty"`
}

type RedirectParameters struct {

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	KeepContext *bool `json:"keepContext,omitempty" tf:"keep_context,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `static`
	// - `flow`
	// Defaults to `flow`.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TargetFlow *string `json:"targetFlow,omitempty" tf:"target_flow,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TargetStatic *string `json:"targetStatic,omitempty" tf:"target_static,omitempty"`
}

// RedirectSpec defines the desired state of Redirect
type RedirectSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RedirectParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RedirectInitParameters `json:"initProvider,omitempty"`
}

// RedirectStatus defines the observed state of Redirect.
type RedirectStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RedirectObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Redirect is the Schema for the Redirects API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Redirect struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   RedirectSpec   `json:"spec"`
	Status RedirectStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RedirectList contains a list of Redirects
type RedirectList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Redirect `json:"items"`
}

// Repository type metadata.
var (
	Redirect_Kind             = "Redirect"
	Redirect_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Redirect_Kind}.String()
	Redirect_KindAPIVersion   = Redirect_Kind + "." + CRDGroupVersion.String()
	Redirect_GroupVersionKind = CRDGroupVersion.WithKind(Redirect_Kind)
)

func init() {
	SchemeBuilder.Register(&Redirect{}, &RedirectList{})
}
