apiVersion: providers.authentik.crossplane.io/v1alpha1
kind: LDAP
metadata:
  annotations:
    meta.upbound.io/example-id: providers/v1alpha1/ldap
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    baseDn: dc=ldap,dc=goauthentik,dc=io
    bindFlowSelector:
      matchLabels:
        testing.upbound.io/example-name: authentik_flow
    name: ldap-app

---

apiVersion: applications.authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: providers/v1alpha1/ldap
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: ldap-app
    protocolProviderSelector:
      matchLabels:
        testing.upbound.io/example-name: name
    slug: ldap-app
