apiVersion: providers.authentik.crossplane.io/v1alpha1
kind: SCIM
metadata:
  annotations:
    meta.upbound.io/example-id: providers/v1alpha1/scim
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: test-app
    propertyMappingsGroupRefs:
    - name: authentik_property_mapping_scim
    propertyMappingsRefs:
    - name: authentik_property_mapping_scim
    tokenSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    url: http://localhost
