// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *PolicyBinding) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyDummy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyEventMatcher) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyExpiry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyExpression) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyGeoip) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyPassword) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyReputation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PolicyUniquePassword) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingGoogleWorkspace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingLdap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingMicrosoftEntra) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingNotification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingProviderGoogleWorkspace) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingProviderMicrosoftEntra) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingProviderRac) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingProviderRadius) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingProviderSaml) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingProviderScim) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingProviderScope) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingRac) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingRadius) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingSaml) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingScim) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingSourceKerberos) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingSourceLdap) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingSourceOauth) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingSourcePlex) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingSourceSaml) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PropertyMappingSourceScim) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ScopeMapping) Hub() {}
