// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PolicyPasswordInitParameters struct {

	// (Number)
	AmountDigits *float64 `json:"amountDigits,omitempty" tf:"amount_digits,omitempty"`

	// (Number)
	AmountLowercase *float64 `json:"amountLowercase,omitempty" tf:"amount_lowercase,omitempty"`

	// (Number)
	AmountSymbols *float64 `json:"amountSymbols,omitempty" tf:"amount_symbols,omitempty"`

	// (Number)
	AmountUppercase *float64 `json:"amountUppercase,omitempty" tf:"amount_uppercase,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	CheckHaveIBeenPwned *bool `json:"checkHaveIBeenPwned,omitempty" tf:"check_have_i_been_pwned,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	CheckStaticRules *bool `json:"checkStaticRules,omitempty" tf:"check_static_rules,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	CheckZxcvbn *bool `json:"checkZxcvbn,omitempty" tf:"check_zxcvbn,omitempty"`

	// (String)
	ErrorMessage *string `json:"errorMessage,omitempty" tf:"error_message,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (Number) Defaults to 1.
	// Defaults to `1`.
	HibpAllowedCount *float64 `json:"hibpAllowedCount,omitempty" tf:"hibp_allowed_count,omitempty"`

	// (Number)
	LengthMin *float64 `json:"lengthMin,omitempty" tf:"length_min,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to password.
	// Defaults to `password`.
	PasswordField *string `json:"passwordField,omitempty" tf:"password_field,omitempty"`

	// ./:;<=>?@[\]^_{|}~`.
	// Defaults to `!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~`.
	SymbolCharset *string `json:"symbolCharset,omitempty" tf:"symbol_charset,omitempty"`

	// (Number) Defaults to 2.
	// Defaults to `2`.
	ZxcvbnScoreThreshold *float64 `json:"zxcvbnScoreThreshold,omitempty" tf:"zxcvbn_score_threshold,omitempty"`
}

type PolicyPasswordObservation struct {

	// (Number)
	AmountDigits *float64 `json:"amountDigits,omitempty" tf:"amount_digits,omitempty"`

	// (Number)
	AmountLowercase *float64 `json:"amountLowercase,omitempty" tf:"amount_lowercase,omitempty"`

	// (Number)
	AmountSymbols *float64 `json:"amountSymbols,omitempty" tf:"amount_symbols,omitempty"`

	// (Number)
	AmountUppercase *float64 `json:"amountUppercase,omitempty" tf:"amount_uppercase,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	CheckHaveIBeenPwned *bool `json:"checkHaveIBeenPwned,omitempty" tf:"check_have_i_been_pwned,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	CheckStaticRules *bool `json:"checkStaticRules,omitempty" tf:"check_static_rules,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	CheckZxcvbn *bool `json:"checkZxcvbn,omitempty" tf:"check_zxcvbn,omitempty"`

	// (String)
	ErrorMessage *string `json:"errorMessage,omitempty" tf:"error_message,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (Number) Defaults to 1.
	// Defaults to `1`.
	HibpAllowedCount *float64 `json:"hibpAllowedCount,omitempty" tf:"hibp_allowed_count,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number)
	LengthMin *float64 `json:"lengthMin,omitempty" tf:"length_min,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to password.
	// Defaults to `password`.
	PasswordField *string `json:"passwordField,omitempty" tf:"password_field,omitempty"`

	// ./:;<=>?@[\]^_{|}~`.
	// Defaults to `!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~`.
	SymbolCharset *string `json:"symbolCharset,omitempty" tf:"symbol_charset,omitempty"`

	// (Number) Defaults to 2.
	// Defaults to `2`.
	ZxcvbnScoreThreshold *float64 `json:"zxcvbnScoreThreshold,omitempty" tf:"zxcvbn_score_threshold,omitempty"`
}

type PolicyPasswordParameters struct {

	// (Number)
	// +kubebuilder:validation:Optional
	AmountDigits *float64 `json:"amountDigits,omitempty" tf:"amount_digits,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	AmountLowercase *float64 `json:"amountLowercase,omitempty" tf:"amount_lowercase,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	AmountSymbols *float64 `json:"amountSymbols,omitempty" tf:"amount_symbols,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	AmountUppercase *float64 `json:"amountUppercase,omitempty" tf:"amount_uppercase,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	CheckHaveIBeenPwned *bool `json:"checkHaveIBeenPwned,omitempty" tf:"check_have_i_been_pwned,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	CheckStaticRules *bool `json:"checkStaticRules,omitempty" tf:"check_static_rules,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	CheckZxcvbn *bool `json:"checkZxcvbn,omitempty" tf:"check_zxcvbn,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ErrorMessage *string `json:"errorMessage,omitempty" tf:"error_message,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	ExecutionLogging *bool `json:"executionLogging,omitempty" tf:"execution_logging,omitempty"`

	// (Number) Defaults to 1.
	// Defaults to `1`.
	// +kubebuilder:validation:Optional
	HibpAllowedCount *float64 `json:"hibpAllowedCount,omitempty" tf:"hibp_allowed_count,omitempty"`

	// (Number)
	// +kubebuilder:validation:Optional
	LengthMin *float64 `json:"lengthMin,omitempty" tf:"length_min,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to password.
	// Defaults to `password`.
	// +kubebuilder:validation:Optional
	PasswordField *string `json:"passwordField,omitempty" tf:"password_field,omitempty"`

	// ./:;<=>?@[\]^_{|}~`.
	// Defaults to `!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~`.
	// +kubebuilder:validation:Optional
	SymbolCharset *string `json:"symbolCharset,omitempty" tf:"symbol_charset,omitempty"`

	// (Number) Defaults to 2.
	// Defaults to `2`.
	// +kubebuilder:validation:Optional
	ZxcvbnScoreThreshold *float64 `json:"zxcvbnScoreThreshold,omitempty" tf:"zxcvbn_score_threshold,omitempty"`
}

// PolicyPasswordSpec defines the desired state of PolicyPassword
type PolicyPasswordSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PolicyPasswordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PolicyPasswordInitParameters `json:"initProvider,omitempty"`
}

// PolicyPasswordStatus defines the observed state of PolicyPassword.
type PolicyPasswordStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PolicyPasswordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PolicyPassword is the Schema for the PolicyPasswords API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type PolicyPassword struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.errorMessage) || (has(self.initProvider) && has(self.initProvider.errorMessage))",message="spec.forProvider.errorMessage is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   PolicyPasswordSpec   `json:"spec"`
	Status PolicyPasswordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PolicyPasswordList contains a list of PolicyPasswords
type PolicyPasswordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PolicyPassword `json:"items"`
}

// Repository type metadata.
var (
	PolicyPassword_Kind             = "PolicyPassword"
	PolicyPassword_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PolicyPassword_Kind}.String()
	PolicyPassword_KindAPIVersion   = PolicyPassword_Kind + "." + CRDGroupVersion.String()
	PolicyPassword_GroupVersionKind = CRDGroupVersion.WithKind(PolicyPassword_Kind)
)

func init() {
	SchemeBuilder.Register(&PolicyPassword{}, &PolicyPasswordList{})
}
