// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type PropertyMappingSamlInitParameters struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	SAMLName *string `json:"samlName,omitempty" tf:"saml_name,omitempty"`
}

type PropertyMappingSamlObservation struct {
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	SAMLName *string `json:"samlName,omitempty" tf:"saml_name,omitempty"`
}

type PropertyMappingSamlParameters struct {

	// +kubebuilder:validation:Optional
	Expression *string `json:"expression,omitempty" tf:"expression,omitempty"`

	// +kubebuilder:validation:Optional
	FriendlyName *string `json:"friendlyName,omitempty" tf:"friendly_name,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	SAMLName *string `json:"samlName,omitempty" tf:"saml_name,omitempty"`
}

// PropertyMappingSamlSpec defines the desired state of PropertyMappingSaml
type PropertyMappingSamlSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PropertyMappingSamlParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PropertyMappingSamlInitParameters `json:"initProvider,omitempty"`
}

// PropertyMappingSamlStatus defines the observed state of PropertyMappingSaml.
type PropertyMappingSamlStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PropertyMappingSamlObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PropertyMappingSaml is the Schema for the PropertyMappingSamls API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type PropertyMappingSaml struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.expression) || (has(self.initProvider) && has(self.initProvider.expression))",message="spec.forProvider.expression is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.samlName) || (has(self.initProvider) && has(self.initProvider.samlName))",message="spec.forProvider.samlName is a required parameter"
	Spec   PropertyMappingSamlSpec   `json:"spec"`
	Status PropertyMappingSamlStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PropertyMappingSamlList contains a list of PropertyMappingSamls
type PropertyMappingSamlList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PropertyMappingSaml `json:"items"`
}

// Repository type metadata.
var (
	PropertyMappingSaml_Kind             = "PropertyMappingSaml"
	PropertyMappingSaml_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PropertyMappingSaml_Kind}.String()
	PropertyMappingSaml_KindAPIVersion   = PropertyMappingSaml_Kind + "." + CRDGroupVersion.String()
	PropertyMappingSaml_GroupVersionKind = CRDGroupVersion.WithKind(PropertyMappingSaml_Kind)
)

func init() {
	SchemeBuilder.Register(&PropertyMappingSaml{}, &PropertyMappingSamlList{})
}
