// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type Oauth2InitParameters struct {

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=1.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=1`.
	AccessCodeValidity *string `json:"accessCodeValidity,omitempty" tf:"access_code_validity,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=10.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=10`.
	AccessTokenValidity *string `json:"accessTokenValidity,omitempty" tf:"access_token_validity,omitempty"`

	// (List of Map of String)
	AllowedRedirectUris []map[string]*string `json:"allowedRedirectUris,omitempty" tf:"allowed_redirect_uris,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// Reference to a Flow in flows to populate authenticationFlow.
	// +kubebuilder:validation:Optional
	AuthenticationFlowRef *v1.Reference `json:"authenticationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authenticationFlow.
	// +kubebuilder:validation:Optional
	AuthenticationFlowSelector *v1.Selector `json:"authenticationFlowSelector,omitempty" tf:"-"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Reference to a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowRef *v1.Reference `json:"authorizationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowSelector *v1.Selector `json:"authorizationFlowSelector,omitempty" tf:"-"`

	// (String)
	BackchannelLogoutURI *string `json:"backchannelLogoutUri,omitempty" tf:"backchannel_logout_uri,omitempty"`

	// (String)
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive) Generated.
	// Generated.
	ClientSecretSecretRef *v1.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// (String) Allowed values:
	// Allowed values:
	// - `confidential`
	// - `public`
	// Defaults to `confidential`.
	ClientType *string `json:"clientType,omitempty" tf:"client_type,omitempty"`

	// (String)
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	IncludeClaimsInIDToken *bool `json:"includeClaimsInIdToken,omitempty" tf:"include_claims_in_id_token,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	InvalidationFlow *string `json:"invalidationFlow,omitempty" tf:"invalidation_flow,omitempty"`

	// Reference to a Flow in flows to populate invalidationFlow.
	// +kubebuilder:validation:Optional
	InvalidationFlowRef *v1.Reference `json:"invalidationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate invalidationFlow.
	// +kubebuilder:validation:Optional
	InvalidationFlowSelector *v1.Selector `json:"invalidationFlowSelector,omitempty" tf:"-"`

	// (String) Allowed values:
	// Allowed values:
	// - `global`
	// - `per_provider`
	// Defaults to `per_provider`.
	IssuerMode *string `json:"issuerMode,omitempty" tf:"issuer_mode,omitempty"`

	// (List of String) Deprecated. Use jwt_federation_sources instead.
	// Deprecated. Use `jwt_federation_sources` instead.
	JwksSources []*string `json:"jwksSources,omitempty" tf:"jwks_sources,omitempty"`

	// (List of Number) JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/providers/v1alpha1.Oauth2
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	// References to Oauth2 in providers to populate jwtFederationProviders.
	// +kubebuilder:validation:Optional
	JwtFederationProvidersRefs []v1.Reference `json:"jwtFederationProvidersRefs,omitempty" tf:"-"`

	// Selector for a list of Oauth2 in providers to populate jwtFederationProviders.
	// +kubebuilder:validation:Optional
	JwtFederationProvidersSelector *v1.Selector `json:"jwtFederationProvidersSelector,omitempty" tf:"-"`

	// (List of String) JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	// JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	JwtFederationSources []*string `json:"jwtFederationSources,omitempty" tf:"jwt_federation_sources,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/propertymapping/v1alpha1.SourceOauth
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// References to SourceOauth in propertymapping to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.Reference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of SourceOauth in propertymapping to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.Selector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to days=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	RefreshTokenValidity *string `json:"refreshTokenValidity,omitempty" tf:"refresh_token_validity,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/system/v1alpha1.CertificateKeyPair
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`

	// Reference to a CertificateKeyPair in system to populate signingKey.
	// +kubebuilder:validation:Optional
	SigningKeyRef *v1.Reference `json:"signingKeyRef,omitempty" tf:"-"`

	// Selector for a CertificateKeyPair in system to populate signingKey.
	// +kubebuilder:validation:Optional
	SigningKeySelector *v1.Selector `json:"signingKeySelector,omitempty" tf:"-"`

	// (String) Allowed values:
	// Allowed values:
	// - `hashed_user_id`
	// - `user_id`
	// - `user_uuid`
	// - `user_username`
	// - `user_email`
	// - `user_upn`
	// Defaults to `hashed_user_id`.
	SubMode *string `json:"subMode,omitempty" tf:"sub_mode,omitempty"`
}

type Oauth2Observation struct {

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=1.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=1`.
	AccessCodeValidity *string `json:"accessCodeValidity,omitempty" tf:"access_code_validity,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=10.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=10`.
	AccessTokenValidity *string `json:"accessTokenValidity,omitempty" tf:"access_token_validity,omitempty"`

	// (List of Map of String)
	AllowedRedirectUris []map[string]*string `json:"allowedRedirectUris,omitempty" tf:"allowed_redirect_uris,omitempty"`

	// (String)
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// (String)
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// (String)
	BackchannelLogoutURI *string `json:"backchannelLogoutUri,omitempty" tf:"backchannel_logout_uri,omitempty"`

	// (String)
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `confidential`
	// - `public`
	// Defaults to `confidential`.
	ClientType *string `json:"clientType,omitempty" tf:"client_type,omitempty"`

	// (String)
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	IncludeClaimsInIDToken *bool `json:"includeClaimsInIdToken,omitempty" tf:"include_claims_in_id_token,omitempty"`

	// (String)
	InvalidationFlow *string `json:"invalidationFlow,omitempty" tf:"invalidation_flow,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `global`
	// - `per_provider`
	// Defaults to `per_provider`.
	IssuerMode *string `json:"issuerMode,omitempty" tf:"issuer_mode,omitempty"`

	// (List of String) Deprecated. Use jwt_federation_sources instead.
	// Deprecated. Use `jwt_federation_sources` instead.
	JwksSources []*string `json:"jwksSources,omitempty" tf:"jwks_sources,omitempty"`

	// (List of Number) JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	// (List of String) JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	// JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	JwtFederationSources []*string `json:"jwtFederationSources,omitempty" tf:"jwt_federation_sources,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to days=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	RefreshTokenValidity *string `json:"refreshTokenValidity,omitempty" tf:"refresh_token_validity,omitempty"`

	// (String)
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `hashed_user_id`
	// - `user_id`
	// - `user_uuid`
	// - `user_username`
	// - `user_email`
	// - `user_upn`
	// Defaults to `hashed_user_id`.
	SubMode *string `json:"subMode,omitempty" tf:"sub_mode,omitempty"`
}

type Oauth2Parameters struct {

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=1.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=1`.
	// +kubebuilder:validation:Optional
	AccessCodeValidity *string `json:"accessCodeValidity,omitempty" tf:"access_code_validity,omitempty"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to minutes=10.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `minutes=10`.
	// +kubebuilder:validation:Optional
	AccessTokenValidity *string `json:"accessTokenValidity,omitempty" tf:"access_token_validity,omitempty"`

	// (List of Map of String)
	// +kubebuilder:validation:Optional
	AllowedRedirectUris []map[string]*string `json:"allowedRedirectUris,omitempty" tf:"allowed_redirect_uris,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	AuthenticationFlow *string `json:"authenticationFlow,omitempty" tf:"authentication_flow,omitempty"`

	// Reference to a Flow in flows to populate authenticationFlow.
	// +kubebuilder:validation:Optional
	AuthenticationFlowRef *v1.Reference `json:"authenticationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authenticationFlow.
	// +kubebuilder:validation:Optional
	AuthenticationFlowSelector *v1.Selector `json:"authenticationFlowSelector,omitempty" tf:"-"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	AuthorizationFlow *string `json:"authorizationFlow,omitempty" tf:"authorization_flow,omitempty"`

	// Reference to a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowRef *v1.Reference `json:"authorizationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate authorizationFlow.
	// +kubebuilder:validation:Optional
	AuthorizationFlowSelector *v1.Selector `json:"authorizationFlowSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	BackchannelLogoutURI *string `json:"backchannelLogoutUri,omitempty" tf:"backchannel_logout_uri,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// (String, Sensitive) Generated.
	// Generated.
	// +kubebuilder:validation:Optional
	ClientSecretSecretRef *v1.SecretKeySelector `json:"clientSecretSecretRef,omitempty" tf:"-"`

	// (String) Allowed values:
	// Allowed values:
	// - `confidential`
	// - `public`
	// Defaults to `confidential`.
	// +kubebuilder:validation:Optional
	ClientType *string `json:"clientType,omitempty" tf:"client_type,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	EncryptionKey *string `json:"encryptionKey,omitempty" tf:"encryption_key,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	IncludeClaimsInIDToken *bool `json:"includeClaimsInIdToken,omitempty" tf:"include_claims_in_id_token,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	InvalidationFlow *string `json:"invalidationFlow,omitempty" tf:"invalidation_flow,omitempty"`

	// Reference to a Flow in flows to populate invalidationFlow.
	// +kubebuilder:validation:Optional
	InvalidationFlowRef *v1.Reference `json:"invalidationFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate invalidationFlow.
	// +kubebuilder:validation:Optional
	InvalidationFlowSelector *v1.Selector `json:"invalidationFlowSelector,omitempty" tf:"-"`

	// (String) Allowed values:
	// Allowed values:
	// - `global`
	// - `per_provider`
	// Defaults to `per_provider`.
	// +kubebuilder:validation:Optional
	IssuerMode *string `json:"issuerMode,omitempty" tf:"issuer_mode,omitempty"`

	// (List of String) Deprecated. Use jwt_federation_sources instead.
	// Deprecated. Use `jwt_federation_sources` instead.
	// +kubebuilder:validation:Optional
	JwksSources []*string `json:"jwksSources,omitempty" tf:"jwks_sources,omitempty"`

	// (List of Number) JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	// JWTs issued by any of the configured providers can be used to authenticate on behalf of this provider.
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/providers/v1alpha1.Oauth2
	// +kubebuilder:validation:Optional
	JwtFederationProviders []*float64 `json:"jwtFederationProviders,omitempty" tf:"jwt_federation_providers,omitempty"`

	// References to Oauth2 in providers to populate jwtFederationProviders.
	// +kubebuilder:validation:Optional
	JwtFederationProvidersRefs []v1.Reference `json:"jwtFederationProvidersRefs,omitempty" tf:"-"`

	// Selector for a list of Oauth2 in providers to populate jwtFederationProviders.
	// +kubebuilder:validation:Optional
	JwtFederationProvidersSelector *v1.Selector `json:"jwtFederationProvidersSelector,omitempty" tf:"-"`

	// (List of String) JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	// JWTs issued by keys configured in any of the selected sources can be used to authenticate on behalf of this provider.
	// +kubebuilder:validation:Optional
	JwtFederationSources []*string `json:"jwtFederationSources,omitempty" tf:"jwt_federation_sources,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (List of String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/propertymapping/v1alpha1.SourceOauth
	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// References to SourceOauth in propertymapping to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.Reference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of SourceOauth in propertymapping to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.Selector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// (String) Format: hours=1;minutes=2;seconds=3. Defaults to days=30.
	// Format: hours=1;minutes=2;seconds=3. Defaults to `days=30`.
	// +kubebuilder:validation:Optional
	RefreshTokenValidity *string `json:"refreshTokenValidity,omitempty" tf:"refresh_token_validity,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/system/v1alpha1.CertificateKeyPair
	// +kubebuilder:validation:Optional
	SigningKey *string `json:"signingKey,omitempty" tf:"signing_key,omitempty"`

	// Reference to a CertificateKeyPair in system to populate signingKey.
	// +kubebuilder:validation:Optional
	SigningKeyRef *v1.Reference `json:"signingKeyRef,omitempty" tf:"-"`

	// Selector for a CertificateKeyPair in system to populate signingKey.
	// +kubebuilder:validation:Optional
	SigningKeySelector *v1.Selector `json:"signingKeySelector,omitempty" tf:"-"`

	// (String) Allowed values:
	// Allowed values:
	// - `hashed_user_id`
	// - `user_id`
	// - `user_uuid`
	// - `user_username`
	// - `user_email`
	// - `user_upn`
	// Defaults to `hashed_user_id`.
	// +kubebuilder:validation:Optional
	SubMode *string `json:"subMode,omitempty" tf:"sub_mode,omitempty"`
}

// Oauth2Spec defines the desired state of Oauth2
type Oauth2Spec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     Oauth2Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider Oauth2InitParameters `json:"initProvider,omitempty"`
}

// Oauth2Status defines the observed state of Oauth2.
type Oauth2Status struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        Oauth2Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Oauth2 is the Schema for the Oauth2s API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Oauth2 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientId) || (has(self.initProvider) && has(self.initProvider.clientId))",message="spec.forProvider.clientId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   Oauth2Spec   `json:"spec"`
	Status Oauth2Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// Oauth2List contains a list of Oauth2s
type Oauth2List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Oauth2 `json:"items"`
}

// Repository type metadata.
var (
	Oauth2_Kind             = "Oauth2"
	Oauth2_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Oauth2_Kind}.String()
	Oauth2_KindAPIVersion   = Oauth2_Kind + "." + CRDGroupVersion.String()
	Oauth2_GroupVersionKind = CRDGroupVersion.WithKind(Oauth2_Kind)
)

func init() {
	SchemeBuilder.Register(&Oauth2{}, &Oauth2List{})
}
