apiVersion: system.authentik.crossplane.io/v1alpha1
kind: Brand
metadata:
  annotations:
    meta.upbound.io/example-id: system/v1alpha1/brand
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    brandingTitle: test
    default: true
    domain: .
