apiVersion: system.authentik.crossplane.io/v1alpha1
kind: SystemSettings
metadata:
  annotations:
    meta.upbound.io/example-id: system/v1alpha1/systemsettings
  labels:
    testing.upbound.io/example-name: settings
  name: settings
spec:
  forProvider:
    defaultUserChangeUsername: true
