// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type EnterpriseLicenseInitParameters struct {
	KeySecretRef v1.SecretKeySelector `json:"keySecretRef" tf:"-"`
}

type EnterpriseLicenseObservation struct {

	// Generated.
	Expiry *float64 `json:"expiry,omitempty" tf:"expiry,omitempty"`

	// Generated.
	ExternalUsers *float64 `json:"externalUsers,omitempty" tf:"external_users,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Generated.
	InternalUsers *float64 `json:"internalUsers,omitempty" tf:"internal_users,omitempty"`

	// Generated.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type EnterpriseLicenseParameters struct {

	// +kubebuilder:validation:Optional
	KeySecretRef v1.SecretKeySelector `json:"keySecretRef" tf:"-"`
}

// EnterpriseLicenseSpec defines the desired state of EnterpriseLicense
type EnterpriseLicenseSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     EnterpriseLicenseParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider EnterpriseLicenseInitParameters `json:"initProvider,omitempty"`
}

// EnterpriseLicenseStatus defines the observed state of EnterpriseLicense.
type EnterpriseLicenseStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        EnterpriseLicenseObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// EnterpriseLicense is the Schema for the EnterpriseLicenses API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type EnterpriseLicense struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.keySecretRef)",message="spec.forProvider.keySecretRef is a required parameter"
	Spec   EnterpriseLicenseSpec   `json:"spec"`
	Status EnterpriseLicenseStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// EnterpriseLicenseList contains a list of EnterpriseLicenses
type EnterpriseLicenseList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EnterpriseLicense `json:"items"`
}

// Repository type metadata.
var (
	EnterpriseLicense_Kind             = "EnterpriseLicense"
	EnterpriseLicense_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: EnterpriseLicense_Kind}.String()
	EnterpriseLicense_KindAPIVersion   = EnterpriseLicense_Kind + "." + CRDGroupVersion.String()
	EnterpriseLicense_GroupVersionKind = CRDGroupVersion.WithKind(EnterpriseLicense_Kind)
)

func init() {
	SchemeBuilder.Register(&EnterpriseLicense{}, &EnterpriseLicenseList{})
}
