apiVersion: users.authentik.crossplane.io/v1alpha1
kind: Token
metadata:
  annotations:
    meta.upbound.io/example-id: users/v1alpha1/token
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: My secret token
    expires: "2025-01-01T15:04:05Z"
    identifier: my-token
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: name

---

apiVersion: users.authentik.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: users/v1alpha1/token
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: User
    username: user
