// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/unbounded-tech/provider-authentik/apis/authentik/v1alpha1"
	v1alpha11 "github.com/unbounded-tech/provider-authentik/apis/customization/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Group.
func (mg *Group) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.ForProvider.Users),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.UsersRefs,
		Selector:      mg.Spec.ForProvider.UsersSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Users")
	}
	mg.Spec.ForProvider.Users = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.UsersRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromFloatPtrValues(mg.Spec.InitProvider.Users),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.UsersRefs,
		Selector:      mg.Spec.InitProvider.UsersSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Users")
	}
	mg.Spec.InitProvider.Users = reference.ToFloatPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.UsersRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this SourceKerberos.
func (mg *SourceKerberos) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.ForProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthenticationFlow")
	}
	mg.Spec.ForProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.ForProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EnrollmentFlow")
	}
	mg.Spec.ForProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EnrollmentFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.InitProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AuthenticationFlow")
	}
	mg.Spec.InitProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.InitProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.EnrollmentFlow")
	}
	mg.Spec.InitProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EnrollmentFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SourceOauth.
func (mg *SourceOauth) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.ForProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthenticationFlow")
	}
	mg.Spec.ForProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.ForProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EnrollmentFlow")
	}
	mg.Spec.ForProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EnrollmentFlowRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.ForProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &v1alpha11.PropertyMappingSourceOauthList{},
			Managed: &v1alpha11.PropertyMappingSourceOauth{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PropertyMappings")
	}
	mg.Spec.ForProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PropertyMappingsGroup),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.PropertyMappingsGroupRefs,
		Selector:      mg.Spec.ForProvider.PropertyMappingsGroupSelector,
		To: reference.To{
			List:    &v1alpha11.PropertyMappingSourceOauthList{},
			Managed: &v1alpha11.PropertyMappingSourceOauth{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PropertyMappingsGroup")
	}
	mg.Spec.ForProvider.PropertyMappingsGroup = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PropertyMappingsGroupRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.InitProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AuthenticationFlow")
	}
	mg.Spec.InitProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.InitProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.EnrollmentFlow")
	}
	mg.Spec.InitProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EnrollmentFlowRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.InitProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &v1alpha11.PropertyMappingSourceOauthList{},
			Managed: &v1alpha11.PropertyMappingSourceOauth{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PropertyMappings")
	}
	mg.Spec.InitProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PropertyMappingsGroup),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.PropertyMappingsGroupRefs,
		Selector:      mg.Spec.InitProvider.PropertyMappingsGroupSelector,
		To: reference.To{
			List:    &v1alpha11.PropertyMappingSourceOauthList{},
			Managed: &v1alpha11.PropertyMappingSourceOauth{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PropertyMappingsGroup")
	}
	mg.Spec.InitProvider.PropertyMappingsGroup = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PropertyMappingsGroupRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this SourcePlex.
func (mg *SourcePlex) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.ForProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthenticationFlow")
	}
	mg.Spec.ForProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.ForProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EnrollmentFlow")
	}
	mg.Spec.ForProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EnrollmentFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.InitProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AuthenticationFlow")
	}
	mg.Spec.InitProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.InitProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.EnrollmentFlow")
	}
	mg.Spec.InitProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EnrollmentFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SourceSaml.
func (mg *SourceSaml) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var mrsp reference.MultiResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.ForProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthenticationFlow")
	}
	mg.Spec.ForProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.ForProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EnrollmentFlow")
	}
	mg.Spec.ForProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EnrollmentFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PreAuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.PreAuthenticationFlowRef,
		Selector:     mg.Spec.ForProvider.PreAuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PreAuthenticationFlow")
	}
	mg.Spec.ForProvider.PreAuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PreAuthenticationFlowRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.ForProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &v1alpha11.PropertyMappingSourceSamlList{},
			Managed: &v1alpha11.PropertyMappingSourceSaml{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PropertyMappings")
	}
	mg.Spec.ForProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.PropertyMappingsGroup),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.PropertyMappingsGroupRefs,
		Selector:      mg.Spec.ForProvider.PropertyMappingsGroupSelector,
		To: reference.To{
			List:    &v1alpha11.PropertyMappingSourceSamlList{},
			Managed: &v1alpha11.PropertyMappingSourceSaml{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PropertyMappingsGroup")
	}
	mg.Spec.ForProvider.PropertyMappingsGroup = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.PropertyMappingsGroupRefs = mrsp.ResolvedReferences

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.AuthenticationFlowRef,
		Selector:     mg.Spec.InitProvider.AuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AuthenticationFlow")
	}
	mg.Spec.InitProvider.AuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AuthenticationFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.InitProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.EnrollmentFlow")
	}
	mg.Spec.InitProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EnrollmentFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PreAuthenticationFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.PreAuthenticationFlowRef,
		Selector:     mg.Spec.InitProvider.PreAuthenticationFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PreAuthenticationFlow")
	}
	mg.Spec.InitProvider.PreAuthenticationFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PreAuthenticationFlowRef = rsp.ResolvedReference

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PropertyMappings),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.PropertyMappingsRefs,
		Selector:      mg.Spec.InitProvider.PropertyMappingsSelector,
		To: reference.To{
			List:    &v1alpha11.PropertyMappingSourceSamlList{},
			Managed: &v1alpha11.PropertyMappingSourceSaml{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PropertyMappings")
	}
	mg.Spec.InitProvider.PropertyMappings = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PropertyMappingsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.PropertyMappingsGroup),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.PropertyMappingsGroupRefs,
		Selector:      mg.Spec.InitProvider.PropertyMappingsGroupSelector,
		To: reference.To{
			List:    &v1alpha11.PropertyMappingSourceSamlList{},
			Managed: &v1alpha11.PropertyMappingSourceSaml{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PropertyMappingsGroup")
	}
	mg.Spec.InitProvider.PropertyMappingsGroup = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.PropertyMappingsGroupRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this Token.
func (mg *Token) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.ForProvider.User),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.UserRef,
		Selector:     mg.Spec.ForProvider.UserSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.User")
	}
	mg.Spec.ForProvider.User = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UserRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromFloatPtrValue(mg.Spec.InitProvider.User),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.UserRef,
		Selector:     mg.Spec.InitProvider.UserSelector,
		To: reference.To{
			List:    &UserList{},
			Managed: &User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.User")
	}
	mg.Spec.InitProvider.User = reference.ToFloatPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UserRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this User.
func (mg *User) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Groups),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.GroupsRefs,
		Selector:      mg.Spec.ForProvider.GroupsSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Groups")
	}
	mg.Spec.ForProvider.Groups = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.GroupsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Groups),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.GroupsRefs,
		Selector:      mg.Spec.InitProvider.GroupsSelector,
		To: reference.To{
			List:    &GroupList{},
			Managed: &Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Groups")
	}
	mg.Spec.InitProvider.Groups = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.GroupsRefs = mrsp.ResolvedReferences

	return nil
}
