//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Group) DeepCopyInto(out *Group) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Group.
func (in *Group) DeepCopy() *Group {
	if in == nil {
		return nil
	}
	out := new(Group)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Group) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupInitParameters) DeepCopyInto(out *GroupInitParameters) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(string)
		**out = **in
	}
	if in.IsSuperuser != nil {
		in, out := &in.IsSuperuser, &out.IsSuperuser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parent != nil {
		in, out := &in.Parent, &out.Parent
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.UsersRefs != nil {
		in, out := &in.UsersRefs, &out.UsersRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UsersSelector != nil {
		in, out := &in.UsersSelector, &out.UsersSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupInitParameters.
func (in *GroupInitParameters) DeepCopy() *GroupInitParameters {
	if in == nil {
		return nil
	}
	out := new(GroupInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupList) DeepCopyInto(out *GroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Group, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupList.
func (in *GroupList) DeepCopy() *GroupList {
	if in == nil {
		return nil
	}
	out := new(GroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupObservation) DeepCopyInto(out *GroupObservation) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsSuperuser != nil {
		in, out := &in.IsSuperuser, &out.IsSuperuser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parent != nil {
		in, out := &in.Parent, &out.Parent
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupObservation.
func (in *GroupObservation) DeepCopy() *GroupObservation {
	if in == nil {
		return nil
	}
	out := new(GroupObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupParameters) DeepCopyInto(out *GroupParameters) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(string)
		**out = **in
	}
	if in.IsSuperuser != nil {
		in, out := &in.IsSuperuser, &out.IsSuperuser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Parent != nil {
		in, out := &in.Parent, &out.Parent
		*out = new(string)
		**out = **in
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]*float64, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(float64)
				**out = **in
			}
		}
	}
	if in.UsersRefs != nil {
		in, out := &in.UsersRefs, &out.UsersRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.UsersSelector != nil {
		in, out := &in.UsersSelector, &out.UsersSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupParameters.
func (in *GroupParameters) DeepCopy() *GroupParameters {
	if in == nil {
		return nil
	}
	out := new(GroupParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupSpec) DeepCopyInto(out *GroupSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupSpec.
func (in *GroupSpec) DeepCopy() *GroupSpec {
	if in == nil {
		return nil
	}
	out := new(GroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupStatus) DeepCopyInto(out *GroupStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupStatus.
func (in *GroupStatus) DeepCopy() *GroupStatus {
	if in == nil {
		return nil
	}
	out := new(GroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceKerberos) DeepCopyInto(out *SourceKerberos) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceKerberos.
func (in *SourceKerberos) DeepCopy() *SourceKerberos {
	if in == nil {
		return nil
	}
	out := new(SourceKerberos)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceKerberos) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceKerberosInitParameters) DeepCopyInto(out *SourceKerberosInitParameters) {
	*out = *in
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Krb5Conf != nil {
		in, out := &in.Krb5Conf, &out.Krb5Conf
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SpnegoCcache != nil {
		in, out := &in.SpnegoCcache, &out.SpnegoCcache
		*out = new(string)
		**out = **in
	}
	if in.SpnegoKeytabSecretRef != nil {
		in, out := &in.SpnegoKeytabSecretRef, &out.SpnegoKeytabSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SpnegoServerName != nil {
		in, out := &in.SpnegoServerName, &out.SpnegoServerName
		*out = new(string)
		**out = **in
	}
	if in.SyncCcache != nil {
		in, out := &in.SyncCcache, &out.SyncCcache
		*out = new(string)
		**out = **in
	}
	if in.SyncKeytabSecretRef != nil {
		in, out := &in.SyncKeytabSecretRef, &out.SyncKeytabSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SyncPasswordSecretRef != nil {
		in, out := &in.SyncPasswordSecretRef, &out.SyncPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SyncPrincipal != nil {
		in, out := &in.SyncPrincipal, &out.SyncPrincipal
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceKerberosInitParameters.
func (in *SourceKerberosInitParameters) DeepCopy() *SourceKerberosInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceKerberosInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceKerberosList) DeepCopyInto(out *SourceKerberosList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourceKerberos, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceKerberosList.
func (in *SourceKerberosList) DeepCopy() *SourceKerberosList {
	if in == nil {
		return nil
	}
	out := new(SourceKerberosList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceKerberosList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceKerberosObservation) DeepCopyInto(out *SourceKerberosObservation) {
	*out = *in
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Krb5Conf != nil {
		in, out := &in.Krb5Conf, &out.Krb5Conf
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SpnegoCcache != nil {
		in, out := &in.SpnegoCcache, &out.SpnegoCcache
		*out = new(string)
		**out = **in
	}
	if in.SpnegoServerName != nil {
		in, out := &in.SpnegoServerName, &out.SpnegoServerName
		*out = new(string)
		**out = **in
	}
	if in.SyncCcache != nil {
		in, out := &in.SyncCcache, &out.SyncCcache
		*out = new(string)
		**out = **in
	}
	if in.SyncPrincipal != nil {
		in, out := &in.SyncPrincipal, &out.SyncPrincipal
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceKerberosObservation.
func (in *SourceKerberosObservation) DeepCopy() *SourceKerberosObservation {
	if in == nil {
		return nil
	}
	out := new(SourceKerberosObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceKerberosParameters) DeepCopyInto(out *SourceKerberosParameters) {
	*out = *in
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Krb5Conf != nil {
		in, out := &in.Krb5Conf, &out.Krb5Conf
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Realm != nil {
		in, out := &in.Realm, &out.Realm
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SpnegoCcache != nil {
		in, out := &in.SpnegoCcache, &out.SpnegoCcache
		*out = new(string)
		**out = **in
	}
	if in.SpnegoKeytabSecretRef != nil {
		in, out := &in.SpnegoKeytabSecretRef, &out.SpnegoKeytabSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SpnegoServerName != nil {
		in, out := &in.SpnegoServerName, &out.SpnegoServerName
		*out = new(string)
		**out = **in
	}
	if in.SyncCcache != nil {
		in, out := &in.SyncCcache, &out.SyncCcache
		*out = new(string)
		**out = **in
	}
	if in.SyncKeytabSecretRef != nil {
		in, out := &in.SyncKeytabSecretRef, &out.SyncKeytabSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SyncPasswordSecretRef != nil {
		in, out := &in.SyncPasswordSecretRef, &out.SyncPasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.SyncPrincipal != nil {
		in, out := &in.SyncPrincipal, &out.SyncPrincipal
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceKerberosParameters.
func (in *SourceKerberosParameters) DeepCopy() *SourceKerberosParameters {
	if in == nil {
		return nil
	}
	out := new(SourceKerberosParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceKerberosSpec) DeepCopyInto(out *SourceKerberosSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceKerberosSpec.
func (in *SourceKerberosSpec) DeepCopy() *SourceKerberosSpec {
	if in == nil {
		return nil
	}
	out := new(SourceKerberosSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceKerberosStatus) DeepCopyInto(out *SourceKerberosStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceKerberosStatus.
func (in *SourceKerberosStatus) DeepCopy() *SourceKerberosStatus {
	if in == nil {
		return nil
	}
	out := new(SourceKerberosStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceLdap) DeepCopyInto(out *SourceLdap) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceLdap.
func (in *SourceLdap) DeepCopy() *SourceLdap {
	if in == nil {
		return nil
	}
	out := new(SourceLdap)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceLdap) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceLdapInitParameters) DeepCopyInto(out *SourceLdapInitParameters) {
	*out = *in
	if in.AdditionalGroupDn != nil {
		in, out := &in.AdditionalGroupDn, &out.AdditionalGroupDn
		*out = new(string)
		**out = **in
	}
	if in.AdditionalUserDn != nil {
		in, out := &in.AdditionalUserDn, &out.AdditionalUserDn
		*out = new(string)
		**out = **in
	}
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindCn != nil {
		in, out := &in.BindCn, &out.BindCn
		*out = new(string)
		**out = **in
	}
	out.BindPasswordSecretRef = in.BindPasswordSecretRef
	if in.DeleteNotFoundObjects != nil {
		in, out := &in.DeleteNotFoundObjects, &out.DeleteNotFoundObjects
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupMembershipField != nil {
		in, out := &in.GroupMembershipField, &out.GroupMembershipField
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectFilter != nil {
		in, out := &in.GroupObjectFilter, &out.GroupObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.LookupGroupsFromUser != nil {
		in, out := &in.LookupGroupsFromUser, &out.LookupGroupsFromUser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectUniquenessField != nil {
		in, out := &in.ObjectUniquenessField, &out.ObjectUniquenessField
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServerURI != nil {
		in, out := &in.ServerURI, &out.ServerURI
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.Sni != nil {
		in, out := &in.Sni, &out.Sni
		*out = new(bool)
		**out = **in
	}
	if in.StartTLS != nil {
		in, out := &in.StartTLS, &out.StartTLS
		*out = new(bool)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.SyncParentGroup != nil {
		in, out := &in.SyncParentGroup, &out.SyncParentGroup
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMembershipAttribute != nil {
		in, out := &in.UserMembershipAttribute, &out.UserMembershipAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectFilter != nil {
		in, out := &in.UserObjectFilter, &out.UserObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceLdapInitParameters.
func (in *SourceLdapInitParameters) DeepCopy() *SourceLdapInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceLdapInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceLdapList) DeepCopyInto(out *SourceLdapList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourceLdap, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceLdapList.
func (in *SourceLdapList) DeepCopy() *SourceLdapList {
	if in == nil {
		return nil
	}
	out := new(SourceLdapList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceLdapList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceLdapObservation) DeepCopyInto(out *SourceLdapObservation) {
	*out = *in
	if in.AdditionalGroupDn != nil {
		in, out := &in.AdditionalGroupDn, &out.AdditionalGroupDn
		*out = new(string)
		**out = **in
	}
	if in.AdditionalUserDn != nil {
		in, out := &in.AdditionalUserDn, &out.AdditionalUserDn
		*out = new(string)
		**out = **in
	}
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindCn != nil {
		in, out := &in.BindCn, &out.BindCn
		*out = new(string)
		**out = **in
	}
	if in.DeleteNotFoundObjects != nil {
		in, out := &in.DeleteNotFoundObjects, &out.DeleteNotFoundObjects
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupMembershipField != nil {
		in, out := &in.GroupMembershipField, &out.GroupMembershipField
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectFilter != nil {
		in, out := &in.GroupObjectFilter, &out.GroupObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.LookupGroupsFromUser != nil {
		in, out := &in.LookupGroupsFromUser, &out.LookupGroupsFromUser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectUniquenessField != nil {
		in, out := &in.ObjectUniquenessField, &out.ObjectUniquenessField
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServerURI != nil {
		in, out := &in.ServerURI, &out.ServerURI
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.Sni != nil {
		in, out := &in.Sni, &out.Sni
		*out = new(bool)
		**out = **in
	}
	if in.StartTLS != nil {
		in, out := &in.StartTLS, &out.StartTLS
		*out = new(bool)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.SyncParentGroup != nil {
		in, out := &in.SyncParentGroup, &out.SyncParentGroup
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMembershipAttribute != nil {
		in, out := &in.UserMembershipAttribute, &out.UserMembershipAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectFilter != nil {
		in, out := &in.UserObjectFilter, &out.UserObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceLdapObservation.
func (in *SourceLdapObservation) DeepCopy() *SourceLdapObservation {
	if in == nil {
		return nil
	}
	out := new(SourceLdapObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceLdapParameters) DeepCopyInto(out *SourceLdapParameters) {
	*out = *in
	if in.AdditionalGroupDn != nil {
		in, out := &in.AdditionalGroupDn, &out.AdditionalGroupDn
		*out = new(string)
		**out = **in
	}
	if in.AdditionalUserDn != nil {
		in, out := &in.AdditionalUserDn, &out.AdditionalUserDn
		*out = new(string)
		**out = **in
	}
	if in.BaseDn != nil {
		in, out := &in.BaseDn, &out.BaseDn
		*out = new(string)
		**out = **in
	}
	if in.BindCn != nil {
		in, out := &in.BindCn, &out.BindCn
		*out = new(string)
		**out = **in
	}
	out.BindPasswordSecretRef = in.BindPasswordSecretRef
	if in.DeleteNotFoundObjects != nil {
		in, out := &in.DeleteNotFoundObjects, &out.DeleteNotFoundObjects
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.GroupMembershipField != nil {
		in, out := &in.GroupMembershipField, &out.GroupMembershipField
		*out = new(string)
		**out = **in
	}
	if in.GroupObjectFilter != nil {
		in, out := &in.GroupObjectFilter, &out.GroupObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.LookupGroupsFromUser != nil {
		in, out := &in.LookupGroupsFromUser, &out.LookupGroupsFromUser
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ObjectUniquenessField != nil {
		in, out := &in.ObjectUniquenessField, &out.ObjectUniquenessField
		*out = new(string)
		**out = **in
	}
	if in.PasswordLoginUpdateInternalPassword != nil {
		in, out := &in.PasswordLoginUpdateInternalPassword, &out.PasswordLoginUpdateInternalPassword
		*out = new(bool)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ServerURI != nil {
		in, out := &in.ServerURI, &out.ServerURI
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.Sni != nil {
		in, out := &in.Sni, &out.Sni
		*out = new(bool)
		**out = **in
	}
	if in.StartTLS != nil {
		in, out := &in.StartTLS, &out.StartTLS
		*out = new(bool)
		**out = **in
	}
	if in.SyncGroups != nil {
		in, out := &in.SyncGroups, &out.SyncGroups
		*out = new(bool)
		**out = **in
	}
	if in.SyncParentGroup != nil {
		in, out := &in.SyncParentGroup, &out.SyncParentGroup
		*out = new(string)
		**out = **in
	}
	if in.SyncUsers != nil {
		in, out := &in.SyncUsers, &out.SyncUsers
		*out = new(bool)
		**out = **in
	}
	if in.SyncUsersPassword != nil {
		in, out := &in.SyncUsersPassword, &out.SyncUsersPassword
		*out = new(bool)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMembershipAttribute != nil {
		in, out := &in.UserMembershipAttribute, &out.UserMembershipAttribute
		*out = new(string)
		**out = **in
	}
	if in.UserObjectFilter != nil {
		in, out := &in.UserObjectFilter, &out.UserObjectFilter
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceLdapParameters.
func (in *SourceLdapParameters) DeepCopy() *SourceLdapParameters {
	if in == nil {
		return nil
	}
	out := new(SourceLdapParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceLdapSpec) DeepCopyInto(out *SourceLdapSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceLdapSpec.
func (in *SourceLdapSpec) DeepCopy() *SourceLdapSpec {
	if in == nil {
		return nil
	}
	out := new(SourceLdapSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceLdapStatus) DeepCopyInto(out *SourceLdapStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceLdapStatus.
func (in *SourceLdapStatus) DeepCopy() *SourceLdapStatus {
	if in == nil {
		return nil
	}
	out := new(SourceLdapStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceOauth) DeepCopyInto(out *SourceOauth) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceOauth.
func (in *SourceOauth) DeepCopy() *SourceOauth {
	if in == nil {
		return nil
	}
	out := new(SourceOauth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceOauth) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceOauthInitParameters) DeepCopyInto(out *SourceOauthInitParameters) {
	*out = *in
	if in.AccessTokenURL != nil {
		in, out := &in.AccessTokenURL, &out.AccessTokenURL
		*out = new(string)
		**out = **in
	}
	if in.AdditionalScopes != nil {
		in, out := &in.AdditionalScopes, &out.AdditionalScopes
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationCodeAuthMethod != nil {
		in, out := &in.AuthorizationCodeAuthMethod, &out.AuthorizationCodeAuthMethod
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationURL != nil {
		in, out := &in.AuthorizationURL, &out.AuthorizationURL
		*out = new(string)
		**out = **in
	}
	if in.ConsumerKey != nil {
		in, out := &in.ConsumerKey, &out.ConsumerKey
		*out = new(string)
		**out = **in
	}
	out.ConsumerSecretSecretRef = in.ConsumerSecretSecretRef
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OidcJwks != nil {
		in, out := &in.OidcJwks, &out.OidcJwks
		*out = new(string)
		**out = **in
	}
	if in.OidcJwksURL != nil {
		in, out := &in.OidcJwksURL, &out.OidcJwksURL
		*out = new(string)
		**out = **in
	}
	if in.OidcWellKnownURL != nil {
		in, out := &in.OidcWellKnownURL, &out.OidcWellKnownURL
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.ProfileURL != nil {
		in, out := &in.ProfileURL, &out.ProfileURL
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroupRefs != nil {
		in, out := &in.PropertyMappingsGroupRefs, &out.PropertyMappingsGroupRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsGroupSelector != nil {
		in, out := &in.PropertyMappingsGroupSelector, &out.PropertyMappingsGroupSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderType != nil {
		in, out := &in.ProviderType, &out.ProviderType
		*out = new(string)
		**out = **in
	}
	if in.RequestTokenURL != nil {
		in, out := &in.RequestTokenURL, &out.RequestTokenURL
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceOauthInitParameters.
func (in *SourceOauthInitParameters) DeepCopy() *SourceOauthInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceOauthInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceOauthList) DeepCopyInto(out *SourceOauthList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourceOauth, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceOauthList.
func (in *SourceOauthList) DeepCopy() *SourceOauthList {
	if in == nil {
		return nil
	}
	out := new(SourceOauthList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceOauthList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceOauthObservation) DeepCopyInto(out *SourceOauthObservation) {
	*out = *in
	if in.AccessTokenURL != nil {
		in, out := &in.AccessTokenURL, &out.AccessTokenURL
		*out = new(string)
		**out = **in
	}
	if in.AdditionalScopes != nil {
		in, out := &in.AdditionalScopes, &out.AdditionalScopes
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationCodeAuthMethod != nil {
		in, out := &in.AuthorizationCodeAuthMethod, &out.AuthorizationCodeAuthMethod
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationURL != nil {
		in, out := &in.AuthorizationURL, &out.AuthorizationURL
		*out = new(string)
		**out = **in
	}
	if in.CallbackURI != nil {
		in, out := &in.CallbackURI, &out.CallbackURI
		*out = new(string)
		**out = **in
	}
	if in.ConsumerKey != nil {
		in, out := &in.ConsumerKey, &out.ConsumerKey
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OidcJwks != nil {
		in, out := &in.OidcJwks, &out.OidcJwks
		*out = new(string)
		**out = **in
	}
	if in.OidcJwksURL != nil {
		in, out := &in.OidcJwksURL, &out.OidcJwksURL
		*out = new(string)
		**out = **in
	}
	if in.OidcWellKnownURL != nil {
		in, out := &in.OidcWellKnownURL, &out.OidcWellKnownURL
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.ProfileURL != nil {
		in, out := &in.ProfileURL, &out.ProfileURL
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ProviderType != nil {
		in, out := &in.ProviderType, &out.ProviderType
		*out = new(string)
		**out = **in
	}
	if in.RequestTokenURL != nil {
		in, out := &in.RequestTokenURL, &out.RequestTokenURL
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceOauthObservation.
func (in *SourceOauthObservation) DeepCopy() *SourceOauthObservation {
	if in == nil {
		return nil
	}
	out := new(SourceOauthObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceOauthParameters) DeepCopyInto(out *SourceOauthParameters) {
	*out = *in
	if in.AccessTokenURL != nil {
		in, out := &in.AccessTokenURL, &out.AccessTokenURL
		*out = new(string)
		**out = **in
	}
	if in.AdditionalScopes != nil {
		in, out := &in.AdditionalScopes, &out.AdditionalScopes
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthorizationCodeAuthMethod != nil {
		in, out := &in.AuthorizationCodeAuthMethod, &out.AuthorizationCodeAuthMethod
		*out = new(string)
		**out = **in
	}
	if in.AuthorizationURL != nil {
		in, out := &in.AuthorizationURL, &out.AuthorizationURL
		*out = new(string)
		**out = **in
	}
	if in.ConsumerKey != nil {
		in, out := &in.ConsumerKey, &out.ConsumerKey
		*out = new(string)
		**out = **in
	}
	out.ConsumerSecretSecretRef = in.ConsumerSecretSecretRef
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.OidcJwks != nil {
		in, out := &in.OidcJwks, &out.OidcJwks
		*out = new(string)
		**out = **in
	}
	if in.OidcJwksURL != nil {
		in, out := &in.OidcJwksURL, &out.OidcJwksURL
		*out = new(string)
		**out = **in
	}
	if in.OidcWellKnownURL != nil {
		in, out := &in.OidcWellKnownURL, &out.OidcWellKnownURL
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.ProfileURL != nil {
		in, out := &in.ProfileURL, &out.ProfileURL
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroupRefs != nil {
		in, out := &in.PropertyMappingsGroupRefs, &out.PropertyMappingsGroupRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsGroupSelector != nil {
		in, out := &in.PropertyMappingsGroupSelector, &out.PropertyMappingsGroupSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ProviderType != nil {
		in, out := &in.ProviderType, &out.ProviderType
		*out = new(string)
		**out = **in
	}
	if in.RequestTokenURL != nil {
		in, out := &in.RequestTokenURL, &out.RequestTokenURL
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceOauthParameters.
func (in *SourceOauthParameters) DeepCopy() *SourceOauthParameters {
	if in == nil {
		return nil
	}
	out := new(SourceOauthParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceOauthSpec) DeepCopyInto(out *SourceOauthSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceOauthSpec.
func (in *SourceOauthSpec) DeepCopy() *SourceOauthSpec {
	if in == nil {
		return nil
	}
	out := new(SourceOauthSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceOauthStatus) DeepCopyInto(out *SourceOauthStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceOauthStatus.
func (in *SourceOauthStatus) DeepCopy() *SourceOauthStatus {
	if in == nil {
		return nil
	}
	out := new(SourceOauthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePlex) DeepCopyInto(out *SourcePlex) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePlex.
func (in *SourcePlex) DeepCopy() *SourcePlex {
	if in == nil {
		return nil
	}
	out := new(SourcePlex)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourcePlex) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePlexInitParameters) DeepCopyInto(out *SourcePlexInitParameters) {
	*out = *in
	if in.AllowFriends != nil {
		in, out := &in.AllowFriends, &out.AllowFriends
		*out = new(bool)
		**out = **in
	}
	if in.AllowedServers != nil {
		in, out := &in.AllowedServers, &out.AllowedServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	out.PlexTokenSecretRef = in.PlexTokenSecretRef
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePlexInitParameters.
func (in *SourcePlexInitParameters) DeepCopy() *SourcePlexInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourcePlexInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePlexList) DeepCopyInto(out *SourcePlexList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourcePlex, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePlexList.
func (in *SourcePlexList) DeepCopy() *SourcePlexList {
	if in == nil {
		return nil
	}
	out := new(SourcePlexList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourcePlexList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePlexObservation) DeepCopyInto(out *SourcePlexObservation) {
	*out = *in
	if in.AllowFriends != nil {
		in, out := &in.AllowFriends, &out.AllowFriends
		*out = new(bool)
		**out = **in
	}
	if in.AllowedServers != nil {
		in, out := &in.AllowedServers, &out.AllowedServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePlexObservation.
func (in *SourcePlexObservation) DeepCopy() *SourcePlexObservation {
	if in == nil {
		return nil
	}
	out := new(SourcePlexObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePlexParameters) DeepCopyInto(out *SourcePlexParameters) {
	*out = *in
	if in.AllowFriends != nil {
		in, out := &in.AllowFriends, &out.AllowFriends
		*out = new(bool)
		**out = **in
	}
	if in.AllowedServers != nil {
		in, out := &in.AllowedServers, &out.AllowedServers
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ClientID != nil {
		in, out := &in.ClientID, &out.ClientID
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	out.PlexTokenSecretRef = in.PlexTokenSecretRef
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePlexParameters.
func (in *SourcePlexParameters) DeepCopy() *SourcePlexParameters {
	if in == nil {
		return nil
	}
	out := new(SourcePlexParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePlexSpec) DeepCopyInto(out *SourcePlexSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePlexSpec.
func (in *SourcePlexSpec) DeepCopy() *SourcePlexSpec {
	if in == nil {
		return nil
	}
	out := new(SourcePlexSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourcePlexStatus) DeepCopyInto(out *SourcePlexStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourcePlexStatus.
func (in *SourcePlexStatus) DeepCopy() *SourcePlexStatus {
	if in == nil {
		return nil
	}
	out := new(SourcePlexStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSaml) DeepCopyInto(out *SourceSaml) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSaml.
func (in *SourceSaml) DeepCopy() *SourceSaml {
	if in == nil {
		return nil
	}
	out := new(SourceSaml)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceSaml) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSamlInitParameters) DeepCopyInto(out *SourceSamlInitParameters) {
	*out = *in
	if in.AllowIdpInitiated != nil {
		in, out := &in.AllowIdpInitiated, &out.AllowIdpInitiated
		*out = new(bool)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.BindingType != nil {
		in, out := &in.BindingType, &out.BindingType
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDPolicy != nil {
		in, out := &in.NameIDPolicy, &out.NameIDPolicy
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlow != nil {
		in, out := &in.PreAuthenticationFlow, &out.PreAuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlowRef != nil {
		in, out := &in.PreAuthenticationFlowRef, &out.PreAuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.PreAuthenticationFlowSelector != nil {
		in, out := &in.PreAuthenticationFlowSelector, &out.PreAuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroupRefs != nil {
		in, out := &in.PropertyMappingsGroupRefs, &out.PropertyMappingsGroupRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsGroupSelector != nil {
		in, out := &in.PropertyMappingsGroupSelector, &out.PropertyMappingsGroupSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SLOURL != nil {
		in, out := &in.SLOURL, &out.SLOURL
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SsoURL != nil {
		in, out := &in.SsoURL, &out.SsoURL
		*out = new(string)
		**out = **in
	}
	if in.TemporaryUserDeleteAfter != nil {
		in, out := &in.TemporaryUserDeleteAfter, &out.TemporaryUserDeleteAfter
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSamlInitParameters.
func (in *SourceSamlInitParameters) DeepCopy() *SourceSamlInitParameters {
	if in == nil {
		return nil
	}
	out := new(SourceSamlInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSamlList) DeepCopyInto(out *SourceSamlList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SourceSaml, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSamlList.
func (in *SourceSamlList) DeepCopy() *SourceSamlList {
	if in == nil {
		return nil
	}
	out := new(SourceSamlList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SourceSamlList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSamlObservation) DeepCopyInto(out *SourceSamlObservation) {
	*out = *in
	if in.AllowIdpInitiated != nil {
		in, out := &in.AllowIdpInitiated, &out.AllowIdpInitiated
		*out = new(bool)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.BindingType != nil {
		in, out := &in.BindingType, &out.BindingType
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDPolicy != nil {
		in, out := &in.NameIDPolicy, &out.NameIDPolicy
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlow != nil {
		in, out := &in.PreAuthenticationFlow, &out.PreAuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SLOURL != nil {
		in, out := &in.SLOURL, &out.SLOURL
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SsoURL != nil {
		in, out := &in.SsoURL, &out.SsoURL
		*out = new(string)
		**out = **in
	}
	if in.TemporaryUserDeleteAfter != nil {
		in, out := &in.TemporaryUserDeleteAfter, &out.TemporaryUserDeleteAfter
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSamlObservation.
func (in *SourceSamlObservation) DeepCopy() *SourceSamlObservation {
	if in == nil {
		return nil
	}
	out := new(SourceSamlObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSamlParameters) DeepCopyInto(out *SourceSamlParameters) {
	*out = *in
	if in.AllowIdpInitiated != nil {
		in, out := &in.AllowIdpInitiated, &out.AllowIdpInitiated
		*out = new(bool)
		**out = **in
	}
	if in.AuthenticationFlow != nil {
		in, out := &in.AuthenticationFlow, &out.AuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.AuthenticationFlowRef != nil {
		in, out := &in.AuthenticationFlowRef, &out.AuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticationFlowSelector != nil {
		in, out := &in.AuthenticationFlowSelector, &out.AuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.BindingType != nil {
		in, out := &in.BindingType, &out.BindingType
		*out = new(string)
		**out = **in
	}
	if in.DigestAlgorithm != nil {
		in, out := &in.DigestAlgorithm, &out.DigestAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.EncryptionKp != nil {
		in, out := &in.EncryptionKp, &out.EncryptionKp
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlow != nil {
		in, out := &in.EnrollmentFlow, &out.EnrollmentFlow
		*out = new(string)
		**out = **in
	}
	if in.EnrollmentFlowRef != nil {
		in, out := &in.EnrollmentFlowRef, &out.EnrollmentFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.EnrollmentFlowSelector != nil {
		in, out := &in.EnrollmentFlowSelector, &out.EnrollmentFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.GroupMatchingMode != nil {
		in, out := &in.GroupMatchingMode, &out.GroupMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.NameIDPolicy != nil {
		in, out := &in.NameIDPolicy, &out.NameIDPolicy
		*out = new(string)
		**out = **in
	}
	if in.PolicyEngineMode != nil {
		in, out := &in.PolicyEngineMode, &out.PolicyEngineMode
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlow != nil {
		in, out := &in.PreAuthenticationFlow, &out.PreAuthenticationFlow
		*out = new(string)
		**out = **in
	}
	if in.PreAuthenticationFlowRef != nil {
		in, out := &in.PreAuthenticationFlowRef, &out.PreAuthenticationFlowRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.PreAuthenticationFlowSelector != nil {
		in, out := &in.PreAuthenticationFlowSelector, &out.PreAuthenticationFlowSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappings != nil {
		in, out := &in.PropertyMappings, &out.PropertyMappings
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroup != nil {
		in, out := &in.PropertyMappingsGroup, &out.PropertyMappingsGroup
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.PropertyMappingsGroupRefs != nil {
		in, out := &in.PropertyMappingsGroupRefs, &out.PropertyMappingsGroupRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsGroupSelector != nil {
		in, out := &in.PropertyMappingsGroupSelector, &out.PropertyMappingsGroupSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.PropertyMappingsRefs != nil {
		in, out := &in.PropertyMappingsRefs, &out.PropertyMappingsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PropertyMappingsSelector != nil {
		in, out := &in.PropertyMappingsSelector, &out.PropertyMappingsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SLOURL != nil {
		in, out := &in.SLOURL, &out.SLOURL
		*out = new(string)
		**out = **in
	}
	if in.SignatureAlgorithm != nil {
		in, out := &in.SignatureAlgorithm, &out.SignatureAlgorithm
		*out = new(string)
		**out = **in
	}
	if in.SigningKp != nil {
		in, out := &in.SigningKp, &out.SigningKp
		*out = new(string)
		**out = **in
	}
	if in.Slug != nil {
		in, out := &in.Slug, &out.Slug
		*out = new(string)
		**out = **in
	}
	if in.SsoURL != nil {
		in, out := &in.SsoURL, &out.SsoURL
		*out = new(string)
		**out = **in
	}
	if in.TemporaryUserDeleteAfter != nil {
		in, out := &in.TemporaryUserDeleteAfter, &out.TemporaryUserDeleteAfter
		*out = new(string)
		**out = **in
	}
	if in.UUID != nil {
		in, out := &in.UUID, &out.UUID
		*out = new(string)
		**out = **in
	}
	if in.UserMatchingMode != nil {
		in, out := &in.UserMatchingMode, &out.UserMatchingMode
		*out = new(string)
		**out = **in
	}
	if in.UserPathTemplate != nil {
		in, out := &in.UserPathTemplate, &out.UserPathTemplate
		*out = new(string)
		**out = **in
	}
	if in.VerificationKp != nil {
		in, out := &in.VerificationKp, &out.VerificationKp
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSamlParameters.
func (in *SourceSamlParameters) DeepCopy() *SourceSamlParameters {
	if in == nil {
		return nil
	}
	out := new(SourceSamlParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSamlSpec) DeepCopyInto(out *SourceSamlSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSamlSpec.
func (in *SourceSamlSpec) DeepCopy() *SourceSamlSpec {
	if in == nil {
		return nil
	}
	out := new(SourceSamlSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceSamlStatus) DeepCopyInto(out *SourceSamlStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceSamlStatus.
func (in *SourceSamlStatus) DeepCopy() *SourceSamlStatus {
	if in == nil {
		return nil
	}
	out := new(SourceSamlStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Token) DeepCopyInto(out *Token) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Token.
func (in *Token) DeepCopy() *Token {
	if in == nil {
		return nil
	}
	out := new(Token)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Token) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenInitParameters) DeepCopyInto(out *TokenInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = new(string)
		**out = **in
	}
	if in.Expiring != nil {
		in, out := &in.Expiring, &out.Expiring
		*out = new(bool)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Intent != nil {
		in, out := &in.Intent, &out.Intent
		*out = new(string)
		**out = **in
	}
	if in.RetrieveKey != nil {
		in, out := &in.RetrieveKey, &out.RetrieveKey
		*out = new(bool)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(float64)
		**out = **in
	}
	if in.UserRef != nil {
		in, out := &in.UserRef, &out.UserRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.UserSelector != nil {
		in, out := &in.UserSelector, &out.UserSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenInitParameters.
func (in *TokenInitParameters) DeepCopy() *TokenInitParameters {
	if in == nil {
		return nil
	}
	out := new(TokenInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenList) DeepCopyInto(out *TokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Token, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenList.
func (in *TokenList) DeepCopy() *TokenList {
	if in == nil {
		return nil
	}
	out := new(TokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenObservation) DeepCopyInto(out *TokenObservation) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = new(string)
		**out = **in
	}
	if in.ExpiresIn != nil {
		in, out := &in.ExpiresIn, &out.ExpiresIn
		*out = new(float64)
		**out = **in
	}
	if in.Expiring != nil {
		in, out := &in.Expiring, &out.Expiring
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Intent != nil {
		in, out := &in.Intent, &out.Intent
		*out = new(string)
		**out = **in
	}
	if in.RetrieveKey != nil {
		in, out := &in.RetrieveKey, &out.RetrieveKey
		*out = new(bool)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenObservation.
func (in *TokenObservation) DeepCopy() *TokenObservation {
	if in == nil {
		return nil
	}
	out := new(TokenObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenParameters) DeepCopyInto(out *TokenParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Expires != nil {
		in, out := &in.Expires, &out.Expires
		*out = new(string)
		**out = **in
	}
	if in.Expiring != nil {
		in, out := &in.Expiring, &out.Expiring
		*out = new(bool)
		**out = **in
	}
	if in.Identifier != nil {
		in, out := &in.Identifier, &out.Identifier
		*out = new(string)
		**out = **in
	}
	if in.Intent != nil {
		in, out := &in.Intent, &out.Intent
		*out = new(string)
		**out = **in
	}
	if in.RetrieveKey != nil {
		in, out := &in.RetrieveKey, &out.RetrieveKey
		*out = new(bool)
		**out = **in
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(float64)
		**out = **in
	}
	if in.UserRef != nil {
		in, out := &in.UserRef, &out.UserRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.UserSelector != nil {
		in, out := &in.UserSelector, &out.UserSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenParameters.
func (in *TokenParameters) DeepCopy() *TokenParameters {
	if in == nil {
		return nil
	}
	out := new(TokenParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenSpec) DeepCopyInto(out *TokenSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenSpec.
func (in *TokenSpec) DeepCopy() *TokenSpec {
	if in == nil {
		return nil
	}
	out := new(TokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TokenStatus) DeepCopyInto(out *TokenStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TokenStatus.
func (in *TokenStatus) DeepCopy() *TokenStatus {
	if in == nil {
		return nil
	}
	out := new(TokenStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *User) DeepCopyInto(out *User) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new User.
func (in *User) DeepCopy() *User {
	if in == nil {
		return nil
	}
	out := new(User)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *User) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserInitParameters) DeepCopyInto(out *UserInitParameters) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GroupsRefs != nil {
		in, out := &in.GroupsRefs, &out.GroupsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupsSelector != nil {
		in, out := &in.GroupsSelector, &out.GroupsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IsActive != nil {
		in, out := &in.IsActive, &out.IsActive
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserInitParameters.
func (in *UserInitParameters) DeepCopy() *UserInitParameters {
	if in == nil {
		return nil
	}
	out := new(UserInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserList) DeepCopyInto(out *UserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]User, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserList.
func (in *UserList) DeepCopy() *UserList {
	if in == nil {
		return nil
	}
	out := new(UserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *UserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserObservation) DeepCopyInto(out *UserObservation) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsActive != nil {
		in, out := &in.IsActive, &out.IsActive
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserObservation.
func (in *UserObservation) DeepCopy() *UserObservation {
	if in == nil {
		return nil
	}
	out := new(UserObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserParameters) DeepCopyInto(out *UserParameters) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = new(string)
		**out = **in
	}
	if in.Email != nil {
		in, out := &in.Email, &out.Email
		*out = new(string)
		**out = **in
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.GroupsRefs != nil {
		in, out := &in.GroupsRefs, &out.GroupsRefs
		*out = make([]v1.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupsSelector != nil {
		in, out := &in.GroupsSelector, &out.GroupsSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.IsActive != nil {
		in, out := &in.IsActive, &out.IsActive
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PasswordSecretRef != nil {
		in, out := &in.PasswordSecretRef, &out.PasswordSecretRef
		*out = new(v1.SecretKeySelector)
		**out = **in
	}
	if in.Path != nil {
		in, out := &in.Path, &out.Path
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserParameters.
func (in *UserParameters) DeepCopy() *UserParameters {
	if in == nil {
		return nil
	}
	out := new(UserParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserSpec) DeepCopyInto(out *UserSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserSpec.
func (in *UserSpec) DeepCopy() *UserSpec {
	if in == nil {
		return nil
	}
	out := new(UserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UserStatus) DeepCopyInto(out *UserStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UserStatus.
func (in *UserStatus) DeepCopy() *UserStatus {
	if in == nil {
		return nil
	}
	out := new(UserStatus)
	in.DeepCopyInto(out)
	return out
}
