// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProviderGoogleWorkspaceInitParameters struct {

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	DefaultGroupEmailDomain *string `json:"defaultGroupEmailDomain,omitempty" tf:"default_group_email_domain,omitempty"`

	DelegatedSubject *string `json:"delegatedSubject,omitempty" tf:"delegated_subject,omitempty"`

	// Defaults to `false`.
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	FilterGroup *string `json:"filterGroup,omitempty" tf:"filter_group,omitempty"`

	// Allowed values:
	// - `delete`
	// - `do_nothing`
	// Defaults to `delete`.
	GroupDeleteAction *string `json:"groupDeleteAction,omitempty" tf:"group_delete_action,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/customization/v1alpha1.PropertyMappingGoogleWorkspace
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/customization/v1alpha1.PropertyMappingGoogleWorkspace
	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// References to PropertyMappingGoogleWorkspace in customization to populate propertyMappingsGroup.
	// +kubebuilder:validation:Optional
	PropertyMappingsGroupRefs []v1.Reference `json:"propertyMappingsGroupRefs,omitempty" tf:"-"`

	// Selector for a list of PropertyMappingGoogleWorkspace in customization to populate propertyMappingsGroup.
	// +kubebuilder:validation:Optional
	PropertyMappingsGroupSelector *v1.Selector `json:"propertyMappingsGroupSelector,omitempty" tf:"-"`

	// References to PropertyMappingGoogleWorkspace in customization to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.Reference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of PropertyMappingGoogleWorkspace in customization to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.Selector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// Allowed values:
	// - `do_nothing`
	// - `delete`
	// - `suspend`
	// Defaults to `delete`.
	UserDeleteAction *string `json:"userDeleteAction,omitempty" tf:"user_delete_action,omitempty"`
}

type ProviderGoogleWorkspaceObservation struct {

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	DefaultGroupEmailDomain *string `json:"defaultGroupEmailDomain,omitempty" tf:"default_group_email_domain,omitempty"`

	DelegatedSubject *string `json:"delegatedSubject,omitempty" tf:"delegated_subject,omitempty"`

	// Defaults to `false`.
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	FilterGroup *string `json:"filterGroup,omitempty" tf:"filter_group,omitempty"`

	// Allowed values:
	// - `delete`
	// - `do_nothing`
	// Defaults to `delete`.
	GroupDeleteAction *string `json:"groupDeleteAction,omitempty" tf:"group_delete_action,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// Allowed values:
	// - `do_nothing`
	// - `delete`
	// - `suspend`
	// Defaults to `delete`.
	UserDeleteAction *string `json:"userDeleteAction,omitempty" tf:"user_delete_action,omitempty"`
}

type ProviderGoogleWorkspaceParameters struct {

	// JSON format expected. Use `jsonencode()` to pass objects. Defaults to `{}`.
	// +kubebuilder:validation:Optional
	Credentials *string `json:"credentials,omitempty" tf:"credentials,omitempty"`

	// +kubebuilder:validation:Optional
	DefaultGroupEmailDomain *string `json:"defaultGroupEmailDomain,omitempty" tf:"default_group_email_domain,omitempty"`

	// +kubebuilder:validation:Optional
	DelegatedSubject *string `json:"delegatedSubject,omitempty" tf:"delegated_subject,omitempty"`

	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	DryRun *bool `json:"dryRun,omitempty" tf:"dry_run,omitempty"`

	// +kubebuilder:validation:Optional
	ExcludeUsersServiceAccount *bool `json:"excludeUsersServiceAccount,omitempty" tf:"exclude_users_service_account,omitempty"`

	// +kubebuilder:validation:Optional
	FilterGroup *string `json:"filterGroup,omitempty" tf:"filter_group,omitempty"`

	// Allowed values:
	// - `delete`
	// - `do_nothing`
	// Defaults to `delete`.
	// +kubebuilder:validation:Optional
	GroupDeleteAction *string `json:"groupDeleteAction,omitempty" tf:"group_delete_action,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/customization/v1alpha1.PropertyMappingGoogleWorkspace
	// +kubebuilder:validation:Optional
	PropertyMappings []*string `json:"propertyMappings,omitempty" tf:"property_mappings,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/customization/v1alpha1.PropertyMappingGoogleWorkspace
	// +kubebuilder:validation:Optional
	PropertyMappingsGroup []*string `json:"propertyMappingsGroup,omitempty" tf:"property_mappings_group,omitempty"`

	// References to PropertyMappingGoogleWorkspace in customization to populate propertyMappingsGroup.
	// +kubebuilder:validation:Optional
	PropertyMappingsGroupRefs []v1.Reference `json:"propertyMappingsGroupRefs,omitempty" tf:"-"`

	// Selector for a list of PropertyMappingGoogleWorkspace in customization to populate propertyMappingsGroup.
	// +kubebuilder:validation:Optional
	PropertyMappingsGroupSelector *v1.Selector `json:"propertyMappingsGroupSelector,omitempty" tf:"-"`

	// References to PropertyMappingGoogleWorkspace in customization to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsRefs []v1.Reference `json:"propertyMappingsRefs,omitempty" tf:"-"`

	// Selector for a list of PropertyMappingGoogleWorkspace in customization to populate propertyMappings.
	// +kubebuilder:validation:Optional
	PropertyMappingsSelector *v1.Selector `json:"propertyMappingsSelector,omitempty" tf:"-"`

	// Allowed values:
	// - `do_nothing`
	// - `delete`
	// - `suspend`
	// Defaults to `delete`.
	// +kubebuilder:validation:Optional
	UserDeleteAction *string `json:"userDeleteAction,omitempty" tf:"user_delete_action,omitempty"`
}

// ProviderGoogleWorkspaceSpec defines the desired state of ProviderGoogleWorkspace
type ProviderGoogleWorkspaceSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProviderGoogleWorkspaceParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProviderGoogleWorkspaceInitParameters `json:"initProvider,omitempty"`
}

// ProviderGoogleWorkspaceStatus defines the observed state of ProviderGoogleWorkspace.
type ProviderGoogleWorkspaceStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProviderGoogleWorkspaceObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProviderGoogleWorkspace is the Schema for the ProviderGoogleWorkspaces API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type ProviderGoogleWorkspace struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.defaultGroupEmailDomain) || (has(self.initProvider) && has(self.initProvider.defaultGroupEmailDomain))",message="spec.forProvider.defaultGroupEmailDomain is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProviderGoogleWorkspaceSpec   `json:"spec"`
	Status ProviderGoogleWorkspaceStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProviderGoogleWorkspaceList contains a list of ProviderGoogleWorkspaces
type ProviderGoogleWorkspaceList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProviderGoogleWorkspace `json:"items"`
}

// Repository type metadata.
var (
	ProviderGoogleWorkspace_Kind             = "ProviderGoogleWorkspace"
	ProviderGoogleWorkspace_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProviderGoogleWorkspace_Kind}.String()
	ProviderGoogleWorkspace_KindAPIVersion   = ProviderGoogleWorkspace_Kind + "." + CRDGroupVersion.String()
	ProviderGoogleWorkspace_GroupVersionKind = CRDGroupVersion.WithKind(ProviderGoogleWorkspace_Kind)
)

func init() {
	SchemeBuilder.Register(&ProviderGoogleWorkspace{}, &ProviderGoogleWorkspaceList{})
}
