// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type ProviderLdapInitParameters struct {

	// (String)
	BaseDn *string `json:"baseDn,omitempty" tf:"base_dn,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/authentik/v1alpha1.Flow
	BindFlow *string `json:"bindFlow,omitempty" tf:"bind_flow,omitempty"`

	// Reference to a Flow in authentik to populate bindFlow.
	// +kubebuilder:validation:Optional
	BindFlowRef *v1.Reference `json:"bindFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in authentik to populate bindFlow.
	// +kubebuilder:validation:Optional
	BindFlowSelector *v1.Selector `json:"bindFlowSelector,omitempty" tf:"-"`

	// (String) Defaults to direct.
	// Defaults to `direct`.
	BindMode *string `json:"bindMode,omitempty" tf:"bind_mode,omitempty"`

	// (String)
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (Number) Defaults to 4000.
	// Defaults to `4000`.
	GIDStartNumber *float64 `json:"gidStartNumber,omitempty" tf:"gid_start_number,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	MfaSupport *bool `json:"mfaSupport,omitempty" tf:"mfa_support,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to direct.
	// Defaults to `direct`.
	SearchMode *string `json:"searchMode,omitempty" tf:"search_mode,omitempty"`

	// (String)
	TLSServerName *string `json:"tlsServerName,omitempty" tf:"tls_server_name,omitempty"`

	// (Number) Defaults to 2000.
	// Defaults to `2000`.
	UIDStartNumber *float64 `json:"uidStartNumber,omitempty" tf:"uid_start_number,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/authentik/v1alpha1.Flow
	UnbindFlow *string `json:"unbindFlow,omitempty" tf:"unbind_flow,omitempty"`

	// Reference to a Flow in authentik to populate unbindFlow.
	// +kubebuilder:validation:Optional
	UnbindFlowRef *v1.Reference `json:"unbindFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in authentik to populate unbindFlow.
	// +kubebuilder:validation:Optional
	UnbindFlowSelector *v1.Selector `json:"unbindFlowSelector,omitempty" tf:"-"`
}

type ProviderLdapObservation struct {

	// (String)
	BaseDn *string `json:"baseDn,omitempty" tf:"base_dn,omitempty"`

	// (String)
	BindFlow *string `json:"bindFlow,omitempty" tf:"bind_flow,omitempty"`

	// (String) Defaults to direct.
	// Defaults to `direct`.
	BindMode *string `json:"bindMode,omitempty" tf:"bind_mode,omitempty"`

	// (String)
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (Number) Defaults to 4000.
	// Defaults to `4000`.
	GIDStartNumber *float64 `json:"gidStartNumber,omitempty" tf:"gid_start_number,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	MfaSupport *bool `json:"mfaSupport,omitempty" tf:"mfa_support,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to direct.
	// Defaults to `direct`.
	SearchMode *string `json:"searchMode,omitempty" tf:"search_mode,omitempty"`

	// (String)
	TLSServerName *string `json:"tlsServerName,omitempty" tf:"tls_server_name,omitempty"`

	// (Number) Defaults to 2000.
	// Defaults to `2000`.
	UIDStartNumber *float64 `json:"uidStartNumber,omitempty" tf:"uid_start_number,omitempty"`

	// (String)
	UnbindFlow *string `json:"unbindFlow,omitempty" tf:"unbind_flow,omitempty"`
}

type ProviderLdapParameters struct {

	// (String)
	// +kubebuilder:validation:Optional
	BaseDn *string `json:"baseDn,omitempty" tf:"base_dn,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/authentik/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	BindFlow *string `json:"bindFlow,omitempty" tf:"bind_flow,omitempty"`

	// Reference to a Flow in authentik to populate bindFlow.
	// +kubebuilder:validation:Optional
	BindFlowRef *v1.Reference `json:"bindFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in authentik to populate bindFlow.
	// +kubebuilder:validation:Optional
	BindFlowSelector *v1.Selector `json:"bindFlowSelector,omitempty" tf:"-"`

	// (String) Defaults to direct.
	// Defaults to `direct`.
	// +kubebuilder:validation:Optional
	BindMode *string `json:"bindMode,omitempty" tf:"bind_mode,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Certificate *string `json:"certificate,omitempty" tf:"certificate,omitempty"`

	// (Number) Defaults to 4000.
	// Defaults to `4000`.
	// +kubebuilder:validation:Optional
	GIDStartNumber *float64 `json:"gidStartNumber,omitempty" tf:"gid_start_number,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	MfaSupport *bool `json:"mfaSupport,omitempty" tf:"mfa_support,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Defaults to direct.
	// Defaults to `direct`.
	// +kubebuilder:validation:Optional
	SearchMode *string `json:"searchMode,omitempty" tf:"search_mode,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	TLSServerName *string `json:"tlsServerName,omitempty" tf:"tls_server_name,omitempty"`

	// (Number) Defaults to 2000.
	// Defaults to `2000`.
	// +kubebuilder:validation:Optional
	UIDStartNumber *float64 `json:"uidStartNumber,omitempty" tf:"uid_start_number,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/authentik/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	UnbindFlow *string `json:"unbindFlow,omitempty" tf:"unbind_flow,omitempty"`

	// Reference to a Flow in authentik to populate unbindFlow.
	// +kubebuilder:validation:Optional
	UnbindFlowRef *v1.Reference `json:"unbindFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in authentik to populate unbindFlow.
	// +kubebuilder:validation:Optional
	UnbindFlowSelector *v1.Selector `json:"unbindFlowSelector,omitempty" tf:"-"`
}

// ProviderLdapSpec defines the desired state of ProviderLdap
type ProviderLdapSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ProviderLdapParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ProviderLdapInitParameters `json:"initProvider,omitempty"`
}

// ProviderLdapStatus defines the observed state of ProviderLdap.
type ProviderLdapStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ProviderLdapObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ProviderLdap is the Schema for the ProviderLdaps API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type ProviderLdap struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.baseDn) || (has(self.initProvider) && has(self.initProvider.baseDn))",message="spec.forProvider.baseDn is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ProviderLdapSpec   `json:"spec"`
	Status ProviderLdapStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ProviderLdapList contains a list of ProviderLdaps
type ProviderLdapList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ProviderLdap `json:"items"`
}

// Repository type metadata.
var (
	ProviderLdap_Kind             = "ProviderLdap"
	ProviderLdap_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ProviderLdap_Kind}.String()
	ProviderLdap_KindAPIVersion   = ProviderLdap_Kind + "." + CRDGroupVersion.String()
	ProviderLdap_GroupVersionKind = CRDGroupVersion.WithKind(ProviderLdap_Kind)
)

func init() {
	SchemeBuilder.Register(&ProviderLdap{}, &ProviderLdapList{})
}
