// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorDuo) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorEmail) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorEndpointGdtc) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorSms) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorStatic) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorTotp) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorValidate) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *AuthenticatorWebauthn) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Captcha) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Consent) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Deny) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Dummy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Email) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Identification) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Invitation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *MutualTls) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Password) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Prompt) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *PromptField) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Redirect) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Source) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserDelete) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserLogin) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserLogout) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *UserWrite) Hub() {}
