// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	errors "github.com/pkg/errors"
	v1alpha1 "github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1"
	v1alpha11 "github.com/unbounded-tech/provider-authentik/apis/users/v1alpha1"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AuthenticatorDuo.
func (mg *AuthenticatorDuo) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AuthenticatorEmail.
func (mg *AuthenticatorEmail) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AuthenticatorEndpointGdtc.
func (mg *AuthenticatorEndpointGdtc) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AuthenticatorSms.
func (mg *AuthenticatorSms) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AuthenticatorStatic.
func (mg *AuthenticatorStatic) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AuthenticatorTotp.
func (mg *AuthenticatorTotp) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this AuthenticatorWebauthn.
func (mg *AuthenticatorWebauthn) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Identification.
func (mg *Identification) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CaptchaStage),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.CaptchaStageRef,
		Selector:     mg.Spec.ForProvider.CaptchaStageSelector,
		To: reference.To{
			List:    &CaptchaList{},
			Managed: &Captcha{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CaptchaStage")
	}
	mg.Spec.ForProvider.CaptchaStage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CaptchaStageRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.ForProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EnrollmentFlow")
	}
	mg.Spec.ForProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EnrollmentFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PasswordStage),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.PasswordStageRef,
		Selector:     mg.Spec.ForProvider.PasswordStageSelector,
		To: reference.To{
			List:    &PasswordList{},
			Managed: &Password{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PasswordStage")
	}
	mg.Spec.ForProvider.PasswordStage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PasswordStageRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PasswordlessFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.PasswordlessFlowRef,
		Selector:     mg.Spec.ForProvider.PasswordlessFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PasswordlessFlow")
	}
	mg.Spec.ForProvider.PasswordlessFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PasswordlessFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RecoveryFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.RecoveryFlowRef,
		Selector:     mg.Spec.ForProvider.RecoveryFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RecoveryFlow")
	}
	mg.Spec.ForProvider.RecoveryFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RecoveryFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CaptchaStage),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.CaptchaStageRef,
		Selector:     mg.Spec.InitProvider.CaptchaStageSelector,
		To: reference.To{
			List:    &CaptchaList{},
			Managed: &Captcha{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CaptchaStage")
	}
	mg.Spec.InitProvider.CaptchaStage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CaptchaStageRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EnrollmentFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.EnrollmentFlowRef,
		Selector:     mg.Spec.InitProvider.EnrollmentFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.EnrollmentFlow")
	}
	mg.Spec.InitProvider.EnrollmentFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EnrollmentFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PasswordStage),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.PasswordStageRef,
		Selector:     mg.Spec.InitProvider.PasswordStageSelector,
		To: reference.To{
			List:    &PasswordList{},
			Managed: &Password{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PasswordStage")
	}
	mg.Spec.InitProvider.PasswordStage = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PasswordStageRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PasswordlessFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.PasswordlessFlowRef,
		Selector:     mg.Spec.InitProvider.PasswordlessFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PasswordlessFlow")
	}
	mg.Spec.InitProvider.PasswordlessFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PasswordlessFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RecoveryFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.RecoveryFlowRef,
		Selector:     mg.Spec.InitProvider.RecoveryFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RecoveryFlow")
	}
	mg.Spec.InitProvider.RecoveryFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RecoveryFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Password.
func (mg *Password) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.ConfigureFlowRef,
		Selector:     mg.Spec.ForProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigureFlow")
	}
	mg.Spec.ForProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigureFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigureFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.ConfigureFlowRef,
		Selector:     mg.Spec.InitProvider.ConfigureFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigureFlow")
	}
	mg.Spec.InitProvider.ConfigureFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigureFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Prompt.
func (mg *Prompt) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.Fields),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.ForProvider.FieldsRefs,
		Selector:      mg.Spec.ForProvider.FieldsSelector,
		To: reference.To{
			List:    &PromptFieldList{},
			Managed: &PromptField{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.Fields")
	}
	mg.Spec.ForProvider.Fields = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.FieldsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.Fields),
		Extract:       reference.ExternalName(),
		References:    mg.Spec.InitProvider.FieldsRefs,
		Selector:      mg.Spec.InitProvider.FieldsSelector,
		To: reference.To{
			List:    &PromptFieldList{},
			Managed: &PromptField{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.Fields")
	}
	mg.Spec.InitProvider.Fields = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.FieldsRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this Redirect.
func (mg *Redirect) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TargetFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.TargetFlowRef,
		Selector:     mg.Spec.ForProvider.TargetFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TargetFlow")
	}
	mg.Spec.ForProvider.TargetFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TargetFlowRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TargetFlow),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.TargetFlowRef,
		Selector:     mg.Spec.InitProvider.TargetFlowSelector,
		To: reference.To{
			List:    &v1alpha1.FlowList{},
			Managed: &v1alpha1.Flow{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TargetFlow")
	}
	mg.Spec.InitProvider.TargetFlow = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TargetFlowRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this UserWrite.
func (mg *UserWrite) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CreateUsersGroup),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.ForProvider.CreateUsersGroupRef,
		Selector:     mg.Spec.ForProvider.CreateUsersGroupSelector,
		To: reference.To{
			List:    &v1alpha11.GroupList{},
			Managed: &v1alpha11.Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CreateUsersGroup")
	}
	mg.Spec.ForProvider.CreateUsersGroup = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CreateUsersGroupRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CreateUsersGroup),
		Extract:      reference.ExternalName(),
		Reference:    mg.Spec.InitProvider.CreateUsersGroupRef,
		Selector:     mg.Spec.InitProvider.CreateUsersGroupSelector,
		To: reference.To{
			List:    &v1alpha11.GroupList{},
			Managed: &v1alpha11.Group{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CreateUsersGroup")
	}
	mg.Spec.InitProvider.CreateUsersGroup = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CreateUsersGroupRef = rsp.ResolvedReference

	return nil
}
