// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type IdentificationInitParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/stages/v1alpha1.Captcha
	CaptchaStage *string `json:"captchaStage,omitempty" tf:"captcha_stage,omitempty"`

	// Reference to a Captcha in stages to populate captchaStage.
	// +kubebuilder:validation:Optional
	CaptchaStageRef *v1.Reference `json:"captchaStageRef,omitempty" tf:"-"`

	// Selector for a Captcha in stages to populate captchaStage.
	// +kubebuilder:validation:Optional
	CaptchaStageSelector *v1.Selector `json:"captchaStageSelector,omitempty" tf:"-"`

	// (Boolean)
	CaseInsensitiveMatching *bool `json:"caseInsensitiveMatching,omitempty" tf:"case_insensitive_matching,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	EnableRememberMe *bool `json:"enableRememberMe,omitempty" tf:"enable_remember_me,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	// Reference to a Flow in flows to populate enrollmentFlow.
	// +kubebuilder:validation:Optional
	EnrollmentFlowRef *v1.Reference `json:"enrollmentFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate enrollmentFlow.
	// +kubebuilder:validation:Optional
	EnrollmentFlowSelector *v1.Selector `json:"enrollmentFlowSelector,omitempty" tf:"-"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/stages/v1alpha1.Password
	PasswordStage *string `json:"passwordStage,omitempty" tf:"password_stage,omitempty"`

	// Reference to a Password in stages to populate passwordStage.
	// +kubebuilder:validation:Optional
	PasswordStageRef *v1.Reference `json:"passwordStageRef,omitempty" tf:"-"`

	// Selector for a Password in stages to populate passwordStage.
	// +kubebuilder:validation:Optional
	PasswordStageSelector *v1.Selector `json:"passwordStageSelector,omitempty" tf:"-"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	PasswordlessFlow *string `json:"passwordlessFlow,omitempty" tf:"passwordless_flow,omitempty"`

	// Reference to a Flow in flows to populate passwordlessFlow.
	// +kubebuilder:validation:Optional
	PasswordlessFlowRef *v1.Reference `json:"passwordlessFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate passwordlessFlow.
	// +kubebuilder:validation:Optional
	PasswordlessFlowSelector *v1.Selector `json:"passwordlessFlowSelector,omitempty" tf:"-"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	PretendUserExists *bool `json:"pretendUserExists,omitempty" tf:"pretend_user_exists,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	RecoveryFlow *string `json:"recoveryFlow,omitempty" tf:"recovery_flow,omitempty"`

	// Reference to a Flow in flows to populate recoveryFlow.
	// +kubebuilder:validation:Optional
	RecoveryFlowRef *v1.Reference `json:"recoveryFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate recoveryFlow.
	// +kubebuilder:validation:Optional
	RecoveryFlowSelector *v1.Selector `json:"recoveryFlowSelector,omitempty" tf:"-"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	ShowMatchedUser *bool `json:"showMatchedUser,omitempty" tf:"show_matched_user,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	ShowSourceLabels *bool `json:"showSourceLabels,omitempty" tf:"show_source_labels,omitempty"`

	// (List of String)
	Sources []*string `json:"sources,omitempty" tf:"sources,omitempty"`

	// (List of String)
	UserFields []*string `json:"userFields,omitempty" tf:"user_fields,omitempty"`
}

type IdentificationObservation struct {

	// (String)
	CaptchaStage *string `json:"captchaStage,omitempty" tf:"captcha_stage,omitempty"`

	// (Boolean)
	CaseInsensitiveMatching *bool `json:"caseInsensitiveMatching,omitempty" tf:"case_insensitive_matching,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	EnableRememberMe *bool `json:"enableRememberMe,omitempty" tf:"enable_remember_me,omitempty"`

	// (String)
	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	PasswordStage *string `json:"passwordStage,omitempty" tf:"password_stage,omitempty"`

	// (String)
	PasswordlessFlow *string `json:"passwordlessFlow,omitempty" tf:"passwordless_flow,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	PretendUserExists *bool `json:"pretendUserExists,omitempty" tf:"pretend_user_exists,omitempty"`

	// (String)
	RecoveryFlow *string `json:"recoveryFlow,omitempty" tf:"recovery_flow,omitempty"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	ShowMatchedUser *bool `json:"showMatchedUser,omitempty" tf:"show_matched_user,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	ShowSourceLabels *bool `json:"showSourceLabels,omitempty" tf:"show_source_labels,omitempty"`

	// (List of String)
	Sources []*string `json:"sources,omitempty" tf:"sources,omitempty"`

	// (List of String)
	UserFields []*string `json:"userFields,omitempty" tf:"user_fields,omitempty"`
}

type IdentificationParameters struct {

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/stages/v1alpha1.Captcha
	// +kubebuilder:validation:Optional
	CaptchaStage *string `json:"captchaStage,omitempty" tf:"captcha_stage,omitempty"`

	// Reference to a Captcha in stages to populate captchaStage.
	// +kubebuilder:validation:Optional
	CaptchaStageRef *v1.Reference `json:"captchaStageRef,omitempty" tf:"-"`

	// Selector for a Captcha in stages to populate captchaStage.
	// +kubebuilder:validation:Optional
	CaptchaStageSelector *v1.Selector `json:"captchaStageSelector,omitempty" tf:"-"`

	// (Boolean)
	// +kubebuilder:validation:Optional
	CaseInsensitiveMatching *bool `json:"caseInsensitiveMatching,omitempty" tf:"case_insensitive_matching,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	EnableRememberMe *bool `json:"enableRememberMe,omitempty" tf:"enable_remember_me,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	EnrollmentFlow *string `json:"enrollmentFlow,omitempty" tf:"enrollment_flow,omitempty"`

	// Reference to a Flow in flows to populate enrollmentFlow.
	// +kubebuilder:validation:Optional
	EnrollmentFlowRef *v1.Reference `json:"enrollmentFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate enrollmentFlow.
	// +kubebuilder:validation:Optional
	EnrollmentFlowSelector *v1.Selector `json:"enrollmentFlowSelector,omitempty" tf:"-"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/stages/v1alpha1.Password
	// +kubebuilder:validation:Optional
	PasswordStage *string `json:"passwordStage,omitempty" tf:"password_stage,omitempty"`

	// Reference to a Password in stages to populate passwordStage.
	// +kubebuilder:validation:Optional
	PasswordStageRef *v1.Reference `json:"passwordStageRef,omitempty" tf:"-"`

	// Selector for a Password in stages to populate passwordStage.
	// +kubebuilder:validation:Optional
	PasswordStageSelector *v1.Selector `json:"passwordStageSelector,omitempty" tf:"-"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	PasswordlessFlow *string `json:"passwordlessFlow,omitempty" tf:"passwordless_flow,omitempty"`

	// Reference to a Flow in flows to populate passwordlessFlow.
	// +kubebuilder:validation:Optional
	PasswordlessFlowRef *v1.Reference `json:"passwordlessFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate passwordlessFlow.
	// +kubebuilder:validation:Optional
	PasswordlessFlowSelector *v1.Selector `json:"passwordlessFlowSelector,omitempty" tf:"-"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	PretendUserExists *bool `json:"pretendUserExists,omitempty" tf:"pretend_user_exists,omitempty"`

	// (String)
	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/flows/v1alpha1.Flow
	// +kubebuilder:validation:Optional
	RecoveryFlow *string `json:"recoveryFlow,omitempty" tf:"recovery_flow,omitempty"`

	// Reference to a Flow in flows to populate recoveryFlow.
	// +kubebuilder:validation:Optional
	RecoveryFlowRef *v1.Reference `json:"recoveryFlowRef,omitempty" tf:"-"`

	// Selector for a Flow in flows to populate recoveryFlow.
	// +kubebuilder:validation:Optional
	RecoveryFlowSelector *v1.Selector `json:"recoveryFlowSelector,omitempty" tf:"-"`

	// (Boolean) Defaults to true.
	// Defaults to `true`.
	// +kubebuilder:validation:Optional
	ShowMatchedUser *bool `json:"showMatchedUser,omitempty" tf:"show_matched_user,omitempty"`

	// (Boolean) Defaults to false.
	// Defaults to `false`.
	// +kubebuilder:validation:Optional
	ShowSourceLabels *bool `json:"showSourceLabels,omitempty" tf:"show_source_labels,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	Sources []*string `json:"sources,omitempty" tf:"sources,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	UserFields []*string `json:"userFields,omitempty" tf:"user_fields,omitempty"`
}

// IdentificationSpec defines the desired state of Identification
type IdentificationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IdentificationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IdentificationInitParameters `json:"initProvider,omitempty"`
}

// IdentificationStatus defines the observed state of Identification.
type IdentificationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IdentificationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Identification is the Schema for the Identifications API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type Identification struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   IdentificationSpec   `json:"spec"`
	Status IdentificationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IdentificationList contains a list of Identifications
type IdentificationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Identification `json:"items"`
}

// Repository type metadata.
var (
	Identification_Kind             = "Identification"
	Identification_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Identification_Kind}.String()
	Identification_KindAPIVersion   = Identification_Kind + "." + CRDGroupVersion.String()
	Identification_GroupVersionKind = CRDGroupVersion.WithKind(Identification_Kind)
)

func init() {
	SchemeBuilder.Register(&Identification{}, &IdentificationList{})
}
