// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type MutualTlsInitParameters struct {

	// (String) Allowed values:
	// Allowed values:
	// - `subject`
	// - `common_name`
	// - `email`
	// Defaults to `email`.
	CertAttribute *string `json:"certAttribute,omitempty" tf:"cert_attribute,omitempty"`

	// (List of String)
	CertificateAuthorities []*string `json:"certificateAuthorities,omitempty" tf:"certificate_authorities,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `optional`
	// - `required`
	// Defaults to `optional`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `username`
	// - `email`
	// Defaults to `email`.
	UserAttribute *string `json:"userAttribute,omitempty" tf:"user_attribute,omitempty"`
}

type MutualTlsObservation struct {

	// (String) Allowed values:
	// Allowed values:
	// - `subject`
	// - `common_name`
	// - `email`
	// Defaults to `email`.
	CertAttribute *string `json:"certAttribute,omitempty" tf:"cert_attribute,omitempty"`

	// (List of String)
	CertificateAuthorities []*string `json:"certificateAuthorities,omitempty" tf:"certificate_authorities,omitempty"`

	// (String) The ID of this resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `optional`
	// - `required`
	// Defaults to `optional`.
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `username`
	// - `email`
	// Defaults to `email`.
	UserAttribute *string `json:"userAttribute,omitempty" tf:"user_attribute,omitempty"`
}

type MutualTlsParameters struct {

	// (String) Allowed values:
	// Allowed values:
	// - `subject`
	// - `common_name`
	// - `email`
	// Defaults to `email`.
	// +kubebuilder:validation:Optional
	CertAttribute *string `json:"certAttribute,omitempty" tf:"cert_attribute,omitempty"`

	// (List of String)
	// +kubebuilder:validation:Optional
	CertificateAuthorities []*string `json:"certificateAuthorities,omitempty" tf:"certificate_authorities,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `optional`
	// - `required`
	// Defaults to `optional`.
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// (String)
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Allowed values:
	// Allowed values:
	// - `username`
	// - `email`
	// Defaults to `email`.
	// +kubebuilder:validation:Optional
	UserAttribute *string `json:"userAttribute,omitempty" tf:"user_attribute,omitempty"`
}

// MutualTlsSpec defines the desired state of MutualTls
type MutualTlsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     MutualTlsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MutualTlsInitParameters `json:"initProvider,omitempty"`
}

// MutualTlsStatus defines the observed state of MutualTls.
type MutualTlsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MutualTlsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MutualTls is the Schema for the MutualTlss API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type MutualTls struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   MutualTlsSpec   `json:"spec"`
	Status MutualTlsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MutualTlsList contains a list of MutualTlss
type MutualTlsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MutualTls `json:"items"`
}

// Repository type metadata.
var (
	MutualTls_Kind             = "MutualTls"
	MutualTls_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MutualTls_Kind}.String()
	MutualTls_KindAPIVersion   = MutualTls_Kind + "." + CRDGroupVersion.String()
	MutualTls_GroupVersionKind = CRDGroupVersion.WithKind(MutualTls_Kind)
)

func init() {
	SchemeBuilder.Register(&MutualTls{}, &MutualTlsList{})
}
