// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/apis/common/v1"
)

type RbacInitialPermissionsInitParameters struct {

	// Allowed values:
	// - `user`
	// - `role`
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Permissions []*float64 `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/rbac/v1alpha1.RbacRole
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Reference to a RbacRole in rbac to populate role.
	// +kubebuilder:validation:Optional
	RoleRef *v1.Reference `json:"roleRef,omitempty" tf:"-"`

	// Selector for a RbacRole in rbac to populate role.
	// +kubebuilder:validation:Optional
	RoleSelector *v1.Selector `json:"roleSelector,omitempty" tf:"-"`
}

type RbacInitialPermissionsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Allowed values:
	// - `user`
	// - `role`
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	Permissions []*float64 `json:"permissions,omitempty" tf:"permissions,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`
}

type RbacInitialPermissionsParameters struct {

	// Allowed values:
	// - `user`
	// - `role`
	// +kubebuilder:validation:Optional
	Mode *string `json:"mode,omitempty" tf:"mode,omitempty"`

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// +kubebuilder:validation:Optional
	Permissions []*float64 `json:"permissions,omitempty" tf:"permissions,omitempty"`

	// +crossplane:generate:reference:type=github.com/unbounded-tech/provider-authentik/apis/rbac/v1alpha1.RbacRole
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Reference to a RbacRole in rbac to populate role.
	// +kubebuilder:validation:Optional
	RoleRef *v1.Reference `json:"roleRef,omitempty" tf:"-"`

	// Selector for a RbacRole in rbac to populate role.
	// +kubebuilder:validation:Optional
	RoleSelector *v1.Selector `json:"roleSelector,omitempty" tf:"-"`
}

// RbacInitialPermissionsSpec defines the desired state of RbacInitialPermissions
type RbacInitialPermissionsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     RbacInitialPermissionsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider RbacInitialPermissionsInitParameters `json:"initProvider,omitempty"`
}

// RbacInitialPermissionsStatus defines the observed state of RbacInitialPermissions.
type RbacInitialPermissionsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        RbacInitialPermissionsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// RbacInitialPermissions is the Schema for the RbacInitialPermissionss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,authentik}
type RbacInitialPermissions struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.mode) || (has(self.initProvider) && has(self.initProvider.mode))",message="spec.forProvider.mode is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.permissions) || (has(self.initProvider) && has(self.initProvider.permissions))",message="spec.forProvider.permissions is a required parameter"
	Spec   RbacInitialPermissionsSpec   `json:"spec"`
	Status RbacInitialPermissionsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// RbacInitialPermissionsList contains a list of RbacInitialPermissionss
type RbacInitialPermissionsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []RbacInitialPermissions `json:"items"`
}

// Repository type metadata.
var (
	RbacInitialPermissions_Kind             = "RbacInitialPermissions"
	RbacInitialPermissions_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: RbacInitialPermissions_Kind}.String()
	RbacInitialPermissions_KindAPIVersion   = RbacInitialPermissions_Kind + "." + CRDGroupVersion.String()
	RbacInitialPermissions_GroupVersionKind = CRDGroupVersion.WithKind(RbacInitialPermissions_Kind)
)

func init() {
	SchemeBuilder.Register(&RbacInitialPermissions{}, &RbacInitialPermissionsList{})
}
